# coding: utf-8

"""
    Integra Markets API

    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from integra_markets.api.sentiment_history_api import SentimentHistoryApi


class TestSentimentHistoryApi(unittest.TestCase):
    """SentimentHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SentimentHistoryApi()

    def tearDown(self) -> None:
        pass

    def test_get_market_overlay(self) -> None:
        """Test case for get_market_overlay

        Markets Overlay
        """
        pass

    def test_get_sentiment_daily(self) -> None:
        """Test case for get_sentiment_daily

        Sentiment Daily
        """
        pass

    def test_get_sentiment_history(self) -> None:
        """Test case for get_sentiment_history

        Sentiment History
        """
        pass

    def test_get_sentiment_now(self) -> None:
        """Test case for get_sentiment_now

        Sentiment Now
        """
        pass

    def test_list_commodities(self) -> None:
        """Test case for list_commodities

        List Commodities
        """
        pass


if __name__ == '__main__':
    unittest.main()
