# coding: utf-8

"""
    Integra Markets API

    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from integra_markets.models.ask_response import AskResponse

class TestAskResponse(unittest.TestCase):
    """AskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AskResponse:
        """Test AskResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AskResponse`
        """
        model = AskResponse()
        if include_optional:
            return AskResponse(
                answer = '',
                sources = [
                    None
                    ],
                tool_calls = [
                    None
                    ],
                model = '',
                template_used = ''
            )
        else:
            return AskResponse(
                answer = '',
                sources = [
                    None
                    ],
                tool_calls = [
                    None
                    ],
                model = '',
        )
        """

    def testAskResponse(self):
        """Test AskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
