# coding: utf-8

"""
    Integra Markets API

    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from integra_markets.api.public_v1_api import PublicV1Api


class TestPublicV1Api(unittest.TestCase):
    """PublicV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicV1Api()

    def tearDown(self) -> None:
        pass

    def test_find_historical_analogs(self) -> None:
        """Test case for find_historical_analogs

        Historical Analogs
        """
        pass

    def test_get_brief(self) -> None:
        """Test case for get_brief

        Brief
        """
        pass

    def test_get_narratives(self) -> None:
        """Test case for get_narratives

        Narratives
        """
        pass

    def test_get_sentiment(self) -> None:
        """Test case for get_sentiment

        Sentiment
        """
        pass


if __name__ == '__main__':
    unittest.main()
