# coding: utf-8

"""
    Integra Markets API

    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from integra_markets.models.ask_request import AskRequest

class TestAskRequest(unittest.TestCase):
    """AskRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AskRequest:
        """Test AskRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AskRequest`
        """
        model = AskRequest()
        if include_optional:
            return AskRequest(
                question = '',
                template = '',
                variables = None,
                commodity = '',
                max_tool_calls = 1.0
            )
        else:
            return AskRequest(
        )
        """

    def testAskRequest(self):
        """Test AskRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
