# coding: utf-8

"""
    Integra Markets API

    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from integra_markets.api.divergence_api import DivergenceApi


class TestDivergenceApi(unittest.TestCase):
    """DivergenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DivergenceApi()

    def tearDown(self) -> None:
        pass

    def test_get_divergence(self) -> None:
        """Test case for get_divergence

        Divergence Batch
        """
        pass

    def test_get_divergence_for_topic(self) -> None:
        """Test case for get_divergence_for_topic

        Divergence For Topic
        """
        pass

    def test_list_topics(self) -> None:
        """Test case for list_topics

        List Topics
        """
        pass


if __name__ == '__main__':
    unittest.main()
