# fly.toml app configuration file generated for integra-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "integra-backend"
primary_region = "sjc"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8000
    timeout = "5s"
    type = "http"