# Fly.io Configuration for Integra Markets Frontend
app = "integra-markets-web"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.web"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/"

[static]
  directory = "/usr/share/nginx/html"
