/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AskRequest,
    AskRequestFromJSON,
    AskRequestToJSON,
} from '../models/AskRequest';
import {
    type AskResponse,
    AskResponseFromJSON,
    AskResponseToJSON,
} from '../models/AskResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface AskAgentRequest {
    askRequest: AskRequest;
    authorization?: string | null;
}

export interface ListAgentTemplatesRequest {
    authorization?: string | null;
}

/**
 * 
 */
export class AgentApi extends runtime.BaseAPI {

    /**
     * Creates request options for askAgent without sending the request
     */
    async askAgentRequestOpts(requestParameters: AskAgentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['askRequest'] == null) {
            throw new runtime.RequiredError(
                'askRequest',
                'Required parameter "askRequest" was null or undefined when calling askAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/agent/ask`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AskRequestToJSON(requestParameters['askRequest']),
        };
    }

    /**
     * Ask
     */
    async askAgentRaw(requestParameters: AskAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AskResponse>> {
        const requestOptions = await this.askAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AskResponseFromJSON(jsonValue));
    }

    /**
     * Ask
     */
    async askAgent(requestParameters: AskAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AskResponse> {
        const response = await this.askAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAgentTemplates without sending the request
     */
    async listAgentTemplatesRequestOpts(requestParameters: ListAgentTemplatesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/agent/templates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Templates
     */
    async listAgentTemplatesRaw(requestParameters: ListAgentTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.listAgentTemplatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List Templates
     */
    async listAgentTemplates(requestParameters: ListAgentTemplatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.listAgentTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
