/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateKeyRequest,
    CreateKeyRequestFromJSON,
    CreateKeyRequestToJSON,
} from '../models/CreateKeyRequest';
import {
    type CreateKeyResponse,
    CreateKeyResponseFromJSON,
    CreateKeyResponseToJSON,
} from '../models/CreateKeyResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type KeyRow,
    KeyRowFromJSON,
    KeyRowToJSON,
} from '../models/KeyRow';

export interface CreateKeyApiKeysPostRequest {
    createKeyRequest: CreateKeyRequest;
}

export interface ListKeysApiKeysGetRequest {
    userId: string;
}

export interface RevokeKeyApiKeysKeyIdDeleteRequest {
    keyId: string;
    userId: string;
}

/**
 * ApiKeysApi - interface
 * 
 * @export
 * @interface ApiKeysApiInterface
 */
export interface ApiKeysApiInterface {
    /**
     * Creates request options for createKeyApiKeysPost without sending the request
     * @param {CreateKeyRequest} createKeyRequest 
     * @throws {RequiredError}
     * @memberof ApiKeysApiInterface
     */
    createKeyApiKeysPostRequestOpts(requestParameters: CreateKeyApiKeysPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create Key
     * @param {CreateKeyRequest} createKeyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeysApiInterface
     */
    createKeyApiKeysPostRaw(requestParameters: CreateKeyApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateKeyResponse>>;

    /**
     * Create Key
     */
    createKeyApiKeysPost(requestParameters: CreateKeyApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateKeyResponse>;

    /**
     * Creates request options for listKeysApiKeysGet without sending the request
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof ApiKeysApiInterface
     */
    listKeysApiKeysGetRequestOpts(requestParameters: ListKeysApiKeysGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List Keys
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeysApiInterface
     */
    listKeysApiKeysGetRaw(requestParameters: ListKeysApiKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KeyRow>>>;

    /**
     * List Keys
     */
    listKeysApiKeysGet(requestParameters: ListKeysApiKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KeyRow>>;

    /**
     * Creates request options for revokeKeyApiKeysKeyIdDelete without sending the request
     * @param {string} keyId 
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof ApiKeysApiInterface
     */
    revokeKeyApiKeysKeyIdDeleteRequestOpts(requestParameters: RevokeKeyApiKeysKeyIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Revoke Key
     * @param {string} keyId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeysApiInterface
     */
    revokeKeyApiKeysKeyIdDeleteRaw(requestParameters: RevokeKeyApiKeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Revoke Key
     */
    revokeKeyApiKeysKeyIdDelete(requestParameters: RevokeKeyApiKeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class ApiKeysApi extends runtime.BaseAPI implements ApiKeysApiInterface {

    /**
     * Creates request options for createKeyApiKeysPost without sending the request
     */
    async createKeyApiKeysPostRequestOpts(requestParameters: CreateKeyApiKeysPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'createKeyRequest',
                'Required parameter "createKeyRequest" was null or undefined when calling createKeyApiKeysPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateKeyRequestToJSON(requestParameters['createKeyRequest']),
        };
    }

    /**
     * Create Key
     */
    async createKeyApiKeysPostRaw(requestParameters: CreateKeyApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateKeyResponse>> {
        const requestOptions = await this.createKeyApiKeysPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateKeyResponseFromJSON(jsonValue));
    }

    /**
     * Create Key
     */
    async createKeyApiKeysPost(requestParameters: CreateKeyApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateKeyResponse> {
        const response = await this.createKeyApiKeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listKeysApiKeysGet without sending the request
     */
    async listKeysApiKeysGetRequestOpts(requestParameters: ListKeysApiKeysGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listKeysApiKeysGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/keys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Keys
     */
    async listKeysApiKeysGetRaw(requestParameters: ListKeysApiKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KeyRow>>> {
        const requestOptions = await this.listKeysApiKeysGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KeyRowFromJSON));
    }

    /**
     * List Keys
     */
    async listKeysApiKeysGet(requestParameters: ListKeysApiKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KeyRow>> {
        const response = await this.listKeysApiKeysGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeKeyApiKeysKeyIdDelete without sending the request
     */
    async revokeKeyApiKeysKeyIdDeleteRequestOpts(requestParameters: RevokeKeyApiKeysKeyIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling revokeKeyApiKeysKeyIdDelete().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling revokeKeyApiKeysKeyIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/keys/{key_id}`;
        urlPath = urlPath.replace('{key_id}', encodeURIComponent(String(requestParameters['keyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke Key
     */
    async revokeKeyApiKeysKeyIdDeleteRaw(requestParameters: RevokeKeyApiKeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.revokeKeyApiKeysKeyIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Revoke Key
     */
    async revokeKeyApiKeysKeyIdDelete(requestParameters: RevokeKeyApiKeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.revokeKeyApiKeysKeyIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
