/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AIAnalysisRequest,
    AIAnalysisRequestFromJSON,
    AIAnalysisRequestToJSON,
} from '../models/AIAnalysisRequest';
import {
    type AIChatRequest,
    AIChatRequestFromJSON,
    AIChatRequestToJSON,
} from '../models/AIChatRequest';
import {
    type ArticleSummarizeRequest,
    ArticleSummarizeRequestFromJSON,
    ArticleSummarizeRequestToJSON,
} from '../models/ArticleSummarizeRequest';
import {
    type ComprehensiveAnalysisRequest,
    ComprehensiveAnalysisRequestFromJSON,
    ComprehensiveAnalysisRequestToJSON,
} from '../models/ComprehensiveAnalysisRequest';
import {
    type DashboardSentimentEngineRequest,
    DashboardSentimentEngineRequestFromJSON,
    DashboardSentimentEngineRequestToJSON,
} from '../models/DashboardSentimentEngineRequest';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type LexiconExplainRequest,
    LexiconExplainRequestFromJSON,
    LexiconExplainRequestToJSON,
} from '../models/LexiconExplainRequest';
import {
    type NewsAnalysisRequest,
    NewsAnalysisRequestFromJSON,
    NewsAnalysisRequestToJSON,
} from '../models/NewsAnalysisRequest';
import {
    type NewsRequest,
    NewsRequestFromJSON,
    NewsRequestToJSON,
} from '../models/NewsRequest';
import {
    type OverallSentimentRequest,
    OverallSentimentRequestFromJSON,
    OverallSentimentRequestToJSON,
} from '../models/OverallSentimentRequest';
import {
    type PolymarketConnectorRequest,
    PolymarketConnectorRequestFromJSON,
    PolymarketConnectorRequestToJSON,
} from '../models/PolymarketConnectorRequest';
import {
    type PolymarketConnectorValidationRequest,
    PolymarketConnectorValidationRequestFromJSON,
    PolymarketConnectorValidationRequestToJSON,
} from '../models/PolymarketConnectorValidationRequest';
import {
    type PolymarketSentimentRequest,
    PolymarketSentimentRequestFromJSON,
    PolymarketSentimentRequestToJSON,
} from '../models/PolymarketSentimentRequest';
import {
    type PolymarketSentimentResponse,
    PolymarketSentimentResponseFromJSON,
    PolymarketSentimentResponseToJSON,
} from '../models/PolymarketSentimentResponse';
import {
    type SentimentRequest,
    SentimentRequestFromJSON,
    SentimentRequestToJSON,
} from '../models/SentimentRequest';
import {
    type UserNewsRequest,
    UserNewsRequestFromJSON,
    UserNewsRequestToJSON,
} from '../models/UserNewsRequest';

export interface AiAnalyzeAiAnalyzePostRequest {
    aIAnalysisRequest: AIAnalysisRequest;
}

export interface AiChatAiChatPostRequest {
    aIChatRequest: AIChatRequest;
}

export interface AnalyzeNewsApiNewsAnalysisPostRequest {
    newsAnalysisRequest: NewsAnalysisRequest;
}

export interface AnalyzeSentimentApiSentimentPostRequest {
    sentimentRequest: SentimentRequest;
}

export interface AnalyzeSentimentLegacyAnalyzeSentimentPostRequest {
    sentimentRequest: SentimentRequest;
}

export interface ComprehensiveAnalysisApiComprehensiveAnalysisPostRequest {
    comprehensiveAnalysisRequest: ComprehensiveAnalysisRequest;
}

export interface CreatePolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequest {
    polymarketConnectorRequest: PolymarketConnectorRequest;
}

export interface DeletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequest {
    connectorId: string;
    userId?: string | null;
}

export interface ExplainCommodityLexiconApiLexiconExplainPostRequest {
    lexiconExplainRequest: LexiconExplainRequest;
}

export interface GenerateAiReportAiReportPostRequest {
    includePredictions?: boolean;
    includeNews?: boolean;
    requestBody?: Array<string | null>;
}

export interface GetCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequest {
    commodity: string;
}

export interface GetDashboardSentimentEngineApiDashboardSentimentEnginePostRequest {
    dashboardSentimentEngineRequest: DashboardSentimentEngineRequest;
}

export interface GetNewsFeedApiNewsFeedPostRequest {
    newsRequest: NewsRequest;
}

export interface GetOverallNewsSentimentApiNewsOverallSentimentPostRequest {
    overallSentimentRequest: OverallSentimentRequest;
}

export interface GetPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequest {
    polymarketSentimentRequest: PolymarketSentimentRequest;
}

export interface GetUserNewsApiUserNewsPostRequest {
    userNewsRequest: UserNewsRequest;
}

export interface ListPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequest {
    userId: string;
}

export interface SummarizeArticleApiSummarizeArticlePostRequest {
    articleSummarizeRequest: ArticleSummarizeRequest;
}

export interface ValidatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequest {
    polymarketConnectorValidationRequest: PolymarketConnectorValidationRequest;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * Creates request options for aiAnalyzeAiAnalyzePost without sending the request
     * @param {AIAnalysisRequest} aIAnalysisRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    aiAnalyzeAiAnalyzePostRequestOpts(requestParameters: AiAnalyzeAiAnalyzePostRequest): Promise<runtime.RequestOpts>;

    /**
     * Perform AI analysis with reasoning and tools
     * @summary Ai Analyze
     * @param {AIAnalysisRequest} aIAnalysisRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    aiAnalyzeAiAnalyzePostRaw(requestParameters: AiAnalyzeAiAnalyzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Perform AI analysis with reasoning and tools
     * Ai Analyze
     */
    aiAnalyzeAiAnalyzePost(requestParameters: AiAnalyzeAiAnalyzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for aiChatAiChatPost without sending the request
     * @param {AIChatRequest} aIChatRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    aiChatAiChatPostRequestOpts(requestParameters: AiChatAiChatPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Chat with AI using tool capabilities
     * @summary Ai Chat
     * @param {AIChatRequest} aIChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    aiChatAiChatPostRaw(requestParameters: AiChatAiChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Chat with AI using tool capabilities
     * Ai Chat
     */
    aiChatAiChatPost(requestParameters: AiChatAiChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for analyzeNewsApiNewsAnalysisPost without sending the request
     * @param {NewsAnalysisRequest} newsAnalysisRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    analyzeNewsApiNewsAnalysisPostRequestOpts(requestParameters: AnalyzeNewsApiNewsAnalysisPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Analyze News
     * @param {NewsAnalysisRequest} newsAnalysisRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    analyzeNewsApiNewsAnalysisPostRaw(requestParameters: AnalyzeNewsApiNewsAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Analyze News
     */
    analyzeNewsApiNewsAnalysisPost(requestParameters: AnalyzeNewsApiNewsAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for analyzeSentimentApiSentimentPost without sending the request
     * @param {SentimentRequest} sentimentRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    analyzeSentimentApiSentimentPostRequestOpts(requestParameters: AnalyzeSentimentApiSentimentPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Analyze Sentiment
     * @param {SentimentRequest} sentimentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    analyzeSentimentApiSentimentPostRaw(requestParameters: AnalyzeSentimentApiSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Analyze Sentiment
     */
    analyzeSentimentApiSentimentPost(requestParameters: AnalyzeSentimentApiSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for analyzeSentimentLegacyAnalyzeSentimentPost without sending the request
     * @param {SentimentRequest} sentimentRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    analyzeSentimentLegacyAnalyzeSentimentPostRequestOpts(requestParameters: AnalyzeSentimentLegacyAnalyzeSentimentPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Analyze Sentiment Legacy
     * @param {SentimentRequest} sentimentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    analyzeSentimentLegacyAnalyzeSentimentPostRaw(requestParameters: AnalyzeSentimentLegacyAnalyzeSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Analyze Sentiment Legacy
     */
    analyzeSentimentLegacyAnalyzeSentimentPost(requestParameters: AnalyzeSentimentLegacyAnalyzeSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for comprehensiveAnalysisApiComprehensiveAnalysisPost without sending the request
     * @param {ComprehensiveAnalysisRequest} comprehensiveAnalysisRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    comprehensiveAnalysisApiComprehensiveAnalysisPostRequestOpts(requestParameters: ComprehensiveAnalysisApiComprehensiveAnalysisPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Perform comprehensive analysis with preprocessing and trigger keywords
     * @summary Comprehensive Analysis
     * @param {ComprehensiveAnalysisRequest} comprehensiveAnalysisRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    comprehensiveAnalysisApiComprehensiveAnalysisPostRaw(requestParameters: ComprehensiveAnalysisApiComprehensiveAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Perform comprehensive analysis with preprocessing and trigger keywords
     * Comprehensive Analysis
     */
    comprehensiveAnalysisApiComprehensiveAnalysisPost(requestParameters: ComprehensiveAnalysisApiComprehensiveAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPost without sending the request
     * @param {PolymarketConnectorRequest} polymarketConnectorRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequestOpts(requestParameters: CreatePolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create Polymarket Connector
     * @param {PolymarketConnectorRequest} polymarketConnectorRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRaw(requestParameters: CreatePolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Create Polymarket Connector
     */
    createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPost(requestParameters: CreatePolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDelete without sending the request
     * @param {string} connectorId 
     * @param {string} [userId] 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequestOpts(requestParameters: DeletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete Polymarket Connector
     * @param {string} connectorId 
     * @param {string} [userId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRaw(requestParameters: DeletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Delete Polymarket Connector
     */
    deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDelete(requestParameters: DeletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for explainCommodityLexiconApiLexiconExplainPost without sending the request
     * @param {LexiconExplainRequest} lexiconExplainRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    explainCommodityLexiconApiLexiconExplainPostRequestOpts(requestParameters: ExplainCommodityLexiconApiLexiconExplainPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Explain Commodity Lexicon
     * @param {LexiconExplainRequest} lexiconExplainRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    explainCommodityLexiconApiLexiconExplainPostRaw(requestParameters: ExplainCommodityLexiconApiLexiconExplainPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Explain Commodity Lexicon
     */
    explainCommodityLexiconApiLexiconExplainPost(requestParameters: ExplainCommodityLexiconApiLexiconExplainPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for generateAiReportAiReportPost without sending the request
     * @param {boolean} [includePredictions] 
     * @param {boolean} [includeNews] 
     * @param {Array<string | null>} [requestBody] 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    generateAiReportAiReportPostRequestOpts(requestParameters: GenerateAiReportAiReportPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Generate comprehensive AI market report
     * @summary Generate Ai Report
     * @param {boolean} [includePredictions] 
     * @param {boolean} [includeNews] 
     * @param {Array<string | null>} [requestBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    generateAiReportAiReportPostRaw(requestParameters: GenerateAiReportAiReportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Generate comprehensive AI market report
     * Generate Ai Report
     */
    generateAiReportAiReportPost(requestParameters: GenerateAiReportAiReportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getCommodityLexiconCatalogApiLexiconCommoditiesGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getCommodityLexiconCatalogApiLexiconCommoditiesGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Commodity Lexicon Catalog
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getCommodityLexiconCatalogApiLexiconCommoditiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Commodity Lexicon Catalog
     */
    getCommodityLexiconCatalogApiLexiconCommoditiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getCommodityLexiconDetailApiLexiconCommoditiesCommodityGet without sending the request
     * @param {string} commodity 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequestOpts(requestParameters: GetCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Commodity Lexicon Detail
     * @param {string} commodity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRaw(requestParameters: GetCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Commodity Lexicon Detail
     */
    getCommodityLexiconDetailApiLexiconCommoditiesCommodityGet(requestParameters: GetCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getDashboardSentimentEngineApiDashboardSentimentEnginePost without sending the request
     * @param {DashboardSentimentEngineRequest} dashboardSentimentEngineRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getDashboardSentimentEngineApiDashboardSentimentEnginePostRequestOpts(requestParameters: GetDashboardSentimentEngineApiDashboardSentimentEnginePostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Dashboard Sentiment Engine
     * @param {DashboardSentimentEngineRequest} dashboardSentimentEngineRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getDashboardSentimentEngineApiDashboardSentimentEnginePostRaw(requestParameters: GetDashboardSentimentEngineApiDashboardSentimentEnginePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Dashboard Sentiment Engine
     */
    getDashboardSentimentEngineApiDashboardSentimentEnginePost(requestParameters: GetDashboardSentimentEngineApiDashboardSentimentEnginePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getMarketSentimentApiSentimentMarketGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getMarketSentimentApiSentimentMarketGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Market Sentiment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getMarketSentimentApiSentimentMarketGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Market Sentiment
     */
    getMarketSentimentApiSentimentMarketGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getModelsStatusApiModelsStatusGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getModelsStatusApiModelsStatusGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Models Status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getModelsStatusApiModelsStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Models Status
     */
    getModelsStatusApiModelsStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getNewsFeedApiNewsFeedPost without sending the request
     * @param {NewsRequest} newsRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getNewsFeedApiNewsFeedPostRequestOpts(requestParameters: GetNewsFeedApiNewsFeedPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Fetch real news articles from multiple financial sources
     * @summary Get News Feed
     * @param {NewsRequest} newsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getNewsFeedApiNewsFeedPostRaw(requestParameters: GetNewsFeedApiNewsFeedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Fetch real news articles from multiple financial sources
     * Get News Feed
     */
    getNewsFeedApiNewsFeedPost(requestParameters: GetNewsFeedApiNewsFeedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getOverallNewsSentimentApiNewsOverallSentimentPost without sending the request
     * @param {OverallSentimentRequest} overallSentimentRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getOverallNewsSentimentApiNewsOverallSentimentPostRequestOpts(requestParameters: GetOverallNewsSentimentApiNewsOverallSentimentPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Aggregate the latest cached headlines into a market-level sentiment summary.
     * @summary Get Overall News Sentiment
     * @param {OverallSentimentRequest} overallSentimentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getOverallNewsSentimentApiNewsOverallSentimentPostRaw(requestParameters: GetOverallNewsSentimentApiNewsOverallSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Aggregate the latest cached headlines into a market-level sentiment summary.
     * Get Overall News Sentiment
     */
    getOverallNewsSentimentApiNewsOverallSentimentPost(requestParameters: GetOverallNewsSentimentApiNewsOverallSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPost without sending the request
     * @param {PolymarketSentimentRequest} polymarketSentimentRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequestOpts(requestParameters: GetPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Polymarket Connector Sentiment
     * @param {PolymarketSentimentRequest} polymarketSentimentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRaw(requestParameters: GetPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolymarketSentimentResponse>>;

    /**
     * Get Polymarket Connector Sentiment
     */
    getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPost(requestParameters: GetPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolymarketSentimentResponse>;

    /**
     * Creates request options for getTopMoversApiSentimentMoversGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getTopMoversApiSentimentMoversGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Top Movers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getTopMoversApiSentimentMoversGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Top Movers
     */
    getTopMoversApiSentimentMoversGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getUserNewsApiUserNewsPost without sending the request
     * @param {UserNewsRequest} userNewsRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUserNewsApiUserNewsPostRequestOpts(requestParameters: GetUserNewsApiUserNewsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Fetch personalized news based on user\'s saved preferences in Supabase
     * @summary Get User News
     * @param {UserNewsRequest} userNewsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUserNewsApiUserNewsPostRaw(requestParameters: GetUserNewsApiUserNewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Fetch personalized news based on user\'s saved preferences in Supabase
     * Get User News
     */
    getUserNewsApiUserNewsPost(requestParameters: GetUserNewsApiUserNewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getWeatherAlertsApiWeatherAlertsGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getWeatherAlertsApiWeatherAlertsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Weather Alerts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getWeatherAlertsApiWeatherAlertsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Weather Alerts
     */
    getWeatherAlertsApiWeatherAlertsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for healthCheckHealthGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    healthCheckHealthGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    healthCheckHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Health Check
     */
    healthCheckHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGet without sending the request
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequestOpts(requestParameters: ListPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List Polymarket Connectors
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRaw(requestParameters: ListPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * List Polymarket Connectors
     */
    listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGet(requestParameters: ListPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for readRootGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    readRootGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Read Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    readRootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Read Root
     */
    readRootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for summarizeArticleApiSummarizeArticlePost without sending the request
     * @param {ArticleSummarizeRequest} articleSummarizeRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    summarizeArticleApiSummarizeArticlePostRequestOpts(requestParameters: SummarizeArticleApiSummarizeArticlePostRequest): Promise<runtime.RequestOpts>;

    /**
     * Summarize a financial news article from URL
     * @summary Summarize Article
     * @param {ArticleSummarizeRequest} articleSummarizeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    summarizeArticleApiSummarizeArticlePostRaw(requestParameters: SummarizeArticleApiSummarizeArticlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Summarize a financial news article from URL
     * Summarize Article
     */
    summarizeArticleApiSummarizeArticlePost(requestParameters: SummarizeArticleApiSummarizeArticlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for testNewsEndpointApiTestNewsGet without sending the request
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    testNewsEndpointApiTestNewsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Test endpoint for news functionality
     * @summary Test News Endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    testNewsEndpointApiTestNewsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Test endpoint for news functionality
     * Test News Endpoint
     */
    testNewsEndpointApiTestNewsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePost without sending the request
     * @param {PolymarketConnectorValidationRequest} polymarketConnectorValidationRequest 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequestOpts(requestParameters: ValidatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Validate Polymarket Connector
     * @param {PolymarketConnectorValidationRequest} polymarketConnectorValidationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRaw(requestParameters: ValidatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Validate Polymarket Connector
     */
    validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePost(requestParameters: ValidatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Creates request options for aiAnalyzeAiAnalyzePost without sending the request
     */
    async aiAnalyzeAiAnalyzePostRequestOpts(requestParameters: AiAnalyzeAiAnalyzePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aIAnalysisRequest'] == null) {
            throw new runtime.RequiredError(
                'aIAnalysisRequest',
                'Required parameter "aIAnalysisRequest" was null or undefined when calling aiAnalyzeAiAnalyzePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ai/analyze`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AIAnalysisRequestToJSON(requestParameters['aIAnalysisRequest']),
        };
    }

    /**
     * Perform AI analysis with reasoning and tools
     * Ai Analyze
     */
    async aiAnalyzeAiAnalyzePostRaw(requestParameters: AiAnalyzeAiAnalyzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.aiAnalyzeAiAnalyzePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Perform AI analysis with reasoning and tools
     * Ai Analyze
     */
    async aiAnalyzeAiAnalyzePost(requestParameters: AiAnalyzeAiAnalyzePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.aiAnalyzeAiAnalyzePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for aiChatAiChatPost without sending the request
     */
    async aiChatAiChatPostRequestOpts(requestParameters: AiChatAiChatPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aIChatRequest'] == null) {
            throw new runtime.RequiredError(
                'aIChatRequest',
                'Required parameter "aIChatRequest" was null or undefined when calling aiChatAiChatPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ai/chat`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AIChatRequestToJSON(requestParameters['aIChatRequest']),
        };
    }

    /**
     * Chat with AI using tool capabilities
     * Ai Chat
     */
    async aiChatAiChatPostRaw(requestParameters: AiChatAiChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.aiChatAiChatPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Chat with AI using tool capabilities
     * Ai Chat
     */
    async aiChatAiChatPost(requestParameters: AiChatAiChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.aiChatAiChatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for analyzeNewsApiNewsAnalysisPost without sending the request
     */
    async analyzeNewsApiNewsAnalysisPostRequestOpts(requestParameters: AnalyzeNewsApiNewsAnalysisPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['newsAnalysisRequest'] == null) {
            throw new runtime.RequiredError(
                'newsAnalysisRequest',
                'Required parameter "newsAnalysisRequest" was null or undefined when calling analyzeNewsApiNewsAnalysisPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/news/analysis`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewsAnalysisRequestToJSON(requestParameters['newsAnalysisRequest']),
        };
    }

    /**
     * Analyze News
     */
    async analyzeNewsApiNewsAnalysisPostRaw(requestParameters: AnalyzeNewsApiNewsAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.analyzeNewsApiNewsAnalysisPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Analyze News
     */
    async analyzeNewsApiNewsAnalysisPost(requestParameters: AnalyzeNewsApiNewsAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.analyzeNewsApiNewsAnalysisPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for analyzeSentimentApiSentimentPost without sending the request
     */
    async analyzeSentimentApiSentimentPostRequestOpts(requestParameters: AnalyzeSentimentApiSentimentPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sentimentRequest'] == null) {
            throw new runtime.RequiredError(
                'sentimentRequest',
                'Required parameter "sentimentRequest" was null or undefined when calling analyzeSentimentApiSentimentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sentiment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SentimentRequestToJSON(requestParameters['sentimentRequest']),
        };
    }

    /**
     * Analyze Sentiment
     */
    async analyzeSentimentApiSentimentPostRaw(requestParameters: AnalyzeSentimentApiSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.analyzeSentimentApiSentimentPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Analyze Sentiment
     */
    async analyzeSentimentApiSentimentPost(requestParameters: AnalyzeSentimentApiSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.analyzeSentimentApiSentimentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for analyzeSentimentLegacyAnalyzeSentimentPost without sending the request
     */
    async analyzeSentimentLegacyAnalyzeSentimentPostRequestOpts(requestParameters: AnalyzeSentimentLegacyAnalyzeSentimentPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sentimentRequest'] == null) {
            throw new runtime.RequiredError(
                'sentimentRequest',
                'Required parameter "sentimentRequest" was null or undefined when calling analyzeSentimentLegacyAnalyzeSentimentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/analyze-sentiment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SentimentRequestToJSON(requestParameters['sentimentRequest']),
        };
    }

    /**
     * Analyze Sentiment Legacy
     */
    async analyzeSentimentLegacyAnalyzeSentimentPostRaw(requestParameters: AnalyzeSentimentLegacyAnalyzeSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.analyzeSentimentLegacyAnalyzeSentimentPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Analyze Sentiment Legacy
     */
    async analyzeSentimentLegacyAnalyzeSentimentPost(requestParameters: AnalyzeSentimentLegacyAnalyzeSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.analyzeSentimentLegacyAnalyzeSentimentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for comprehensiveAnalysisApiComprehensiveAnalysisPost without sending the request
     */
    async comprehensiveAnalysisApiComprehensiveAnalysisPostRequestOpts(requestParameters: ComprehensiveAnalysisApiComprehensiveAnalysisPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['comprehensiveAnalysisRequest'] == null) {
            throw new runtime.RequiredError(
                'comprehensiveAnalysisRequest',
                'Required parameter "comprehensiveAnalysisRequest" was null or undefined when calling comprehensiveAnalysisApiComprehensiveAnalysisPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/comprehensive-analysis`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ComprehensiveAnalysisRequestToJSON(requestParameters['comprehensiveAnalysisRequest']),
        };
    }

    /**
     * Perform comprehensive analysis with preprocessing and trigger keywords
     * Comprehensive Analysis
     */
    async comprehensiveAnalysisApiComprehensiveAnalysisPostRaw(requestParameters: ComprehensiveAnalysisApiComprehensiveAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.comprehensiveAnalysisApiComprehensiveAnalysisPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Perform comprehensive analysis with preprocessing and trigger keywords
     * Comprehensive Analysis
     */
    async comprehensiveAnalysisApiComprehensiveAnalysisPost(requestParameters: ComprehensiveAnalysisApiComprehensiveAnalysisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.comprehensiveAnalysisApiComprehensiveAnalysisPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPost without sending the request
     */
    async createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequestOpts(requestParameters: CreatePolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['polymarketConnectorRequest'] == null) {
            throw new runtime.RequiredError(
                'polymarketConnectorRequest',
                'Required parameter "polymarketConnectorRequest" was null or undefined when calling createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/prediction-market/connectors/polymarket`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PolymarketConnectorRequestToJSON(requestParameters['polymarketConnectorRequest']),
        };
    }

    /**
     * Create Polymarket Connector
     */
    async createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRaw(requestParameters: CreatePolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Polymarket Connector
     */
    async createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPost(requestParameters: CreatePolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createPolymarketConnectorApiPredictionMarketConnectorsPolymarketPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDelete without sending the request
     */
    async deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequestOpts(requestParameters: DeletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectorId'] == null) {
            throw new runtime.RequiredError(
                'connectorId',
                'Required parameter "connectorId" was null or undefined when calling deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/prediction-market/connectors/polymarket/{connector_id}`;
        urlPath = urlPath.replace('{connector_id}', encodeURIComponent(String(requestParameters['connectorId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Polymarket Connector
     */
    async deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRaw(requestParameters: DeletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Polymarket Connector
     */
    async deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDelete(requestParameters: DeletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePolymarketConnectorApiPredictionMarketConnectorsPolymarketConnectorIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for explainCommodityLexiconApiLexiconExplainPost without sending the request
     */
    async explainCommodityLexiconApiLexiconExplainPostRequestOpts(requestParameters: ExplainCommodityLexiconApiLexiconExplainPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['lexiconExplainRequest'] == null) {
            throw new runtime.RequiredError(
                'lexiconExplainRequest',
                'Required parameter "lexiconExplainRequest" was null or undefined when calling explainCommodityLexiconApiLexiconExplainPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/lexicon/explain`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LexiconExplainRequestToJSON(requestParameters['lexiconExplainRequest']),
        };
    }

    /**
     * Explain Commodity Lexicon
     */
    async explainCommodityLexiconApiLexiconExplainPostRaw(requestParameters: ExplainCommodityLexiconApiLexiconExplainPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.explainCommodityLexiconApiLexiconExplainPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Explain Commodity Lexicon
     */
    async explainCommodityLexiconApiLexiconExplainPost(requestParameters: ExplainCommodityLexiconApiLexiconExplainPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.explainCommodityLexiconApiLexiconExplainPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for generateAiReportAiReportPost without sending the request
     */
    async generateAiReportAiReportPostRequestOpts(requestParameters: GenerateAiReportAiReportPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['includePredictions'] != null) {
            queryParameters['include_predictions'] = requestParameters['includePredictions'];
        }

        if (requestParameters['includeNews'] != null) {
            queryParameters['include_news'] = requestParameters['includeNews'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ai/report`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Generate comprehensive AI market report
     * Generate Ai Report
     */
    async generateAiReportAiReportPostRaw(requestParameters: GenerateAiReportAiReportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.generateAiReportAiReportPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate comprehensive AI market report
     * Generate Ai Report
     */
    async generateAiReportAiReportPost(requestParameters: GenerateAiReportAiReportPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateAiReportAiReportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommodityLexiconCatalogApiLexiconCommoditiesGet without sending the request
     */
    async getCommodityLexiconCatalogApiLexiconCommoditiesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/lexicon/commodities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Commodity Lexicon Catalog
     */
    async getCommodityLexiconCatalogApiLexiconCommoditiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getCommodityLexiconCatalogApiLexiconCommoditiesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Commodity Lexicon Catalog
     */
    async getCommodityLexiconCatalogApiLexiconCommoditiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getCommodityLexiconCatalogApiLexiconCommoditiesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommodityLexiconDetailApiLexiconCommoditiesCommodityGet without sending the request
     */
    async getCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequestOpts(requestParameters: GetCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling getCommodityLexiconDetailApiLexiconCommoditiesCommodityGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/lexicon/commodities/{commodity}`;
        urlPath = urlPath.replace('{commodity}', encodeURIComponent(String(requestParameters['commodity'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Commodity Lexicon Detail
     */
    async getCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRaw(requestParameters: GetCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Commodity Lexicon Detail
     */
    async getCommodityLexiconDetailApiLexiconCommoditiesCommodityGet(requestParameters: GetCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getCommodityLexiconDetailApiLexiconCommoditiesCommodityGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDashboardSentimentEngineApiDashboardSentimentEnginePost without sending the request
     */
    async getDashboardSentimentEngineApiDashboardSentimentEnginePostRequestOpts(requestParameters: GetDashboardSentimentEngineApiDashboardSentimentEnginePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardSentimentEngineRequest'] == null) {
            throw new runtime.RequiredError(
                'dashboardSentimentEngineRequest',
                'Required parameter "dashboardSentimentEngineRequest" was null or undefined when calling getDashboardSentimentEngineApiDashboardSentimentEnginePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/dashboard/sentiment-engine`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DashboardSentimentEngineRequestToJSON(requestParameters['dashboardSentimentEngineRequest']),
        };
    }

    /**
     * Get Dashboard Sentiment Engine
     */
    async getDashboardSentimentEngineApiDashboardSentimentEnginePostRaw(requestParameters: GetDashboardSentimentEngineApiDashboardSentimentEnginePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getDashboardSentimentEngineApiDashboardSentimentEnginePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Dashboard Sentiment Engine
     */
    async getDashboardSentimentEngineApiDashboardSentimentEnginePost(requestParameters: GetDashboardSentimentEngineApiDashboardSentimentEnginePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDashboardSentimentEngineApiDashboardSentimentEnginePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMarketSentimentApiSentimentMarketGet without sending the request
     */
    async getMarketSentimentApiSentimentMarketGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sentiment/market`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Market Sentiment
     */
    async getMarketSentimentApiSentimentMarketGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getMarketSentimentApiSentimentMarketGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Market Sentiment
     */
    async getMarketSentimentApiSentimentMarketGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getMarketSentimentApiSentimentMarketGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelsStatusApiModelsStatusGet without sending the request
     */
    async getModelsStatusApiModelsStatusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/models/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Models Status
     */
    async getModelsStatusApiModelsStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getModelsStatusApiModelsStatusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Models Status
     */
    async getModelsStatusApiModelsStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getModelsStatusApiModelsStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNewsFeedApiNewsFeedPost without sending the request
     */
    async getNewsFeedApiNewsFeedPostRequestOpts(requestParameters: GetNewsFeedApiNewsFeedPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['newsRequest'] == null) {
            throw new runtime.RequiredError(
                'newsRequest',
                'Required parameter "newsRequest" was null or undefined when calling getNewsFeedApiNewsFeedPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/news/feed`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewsRequestToJSON(requestParameters['newsRequest']),
        };
    }

    /**
     * Fetch real news articles from multiple financial sources
     * Get News Feed
     */
    async getNewsFeedApiNewsFeedPostRaw(requestParameters: GetNewsFeedApiNewsFeedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getNewsFeedApiNewsFeedPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Fetch real news articles from multiple financial sources
     * Get News Feed
     */
    async getNewsFeedApiNewsFeedPost(requestParameters: GetNewsFeedApiNewsFeedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getNewsFeedApiNewsFeedPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOverallNewsSentimentApiNewsOverallSentimentPost without sending the request
     */
    async getOverallNewsSentimentApiNewsOverallSentimentPostRequestOpts(requestParameters: GetOverallNewsSentimentApiNewsOverallSentimentPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['overallSentimentRequest'] == null) {
            throw new runtime.RequiredError(
                'overallSentimentRequest',
                'Required parameter "overallSentimentRequest" was null or undefined when calling getOverallNewsSentimentApiNewsOverallSentimentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/news/overall-sentiment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OverallSentimentRequestToJSON(requestParameters['overallSentimentRequest']),
        };
    }

    /**
     * Aggregate the latest cached headlines into a market-level sentiment summary.
     * Get Overall News Sentiment
     */
    async getOverallNewsSentimentApiNewsOverallSentimentPostRaw(requestParameters: GetOverallNewsSentimentApiNewsOverallSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getOverallNewsSentimentApiNewsOverallSentimentPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Aggregate the latest cached headlines into a market-level sentiment summary.
     * Get Overall News Sentiment
     */
    async getOverallNewsSentimentApiNewsOverallSentimentPost(requestParameters: GetOverallNewsSentimentApiNewsOverallSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getOverallNewsSentimentApiNewsOverallSentimentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPost without sending the request
     */
    async getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequestOpts(requestParameters: GetPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['polymarketSentimentRequest'] == null) {
            throw new runtime.RequiredError(
                'polymarketSentimentRequest',
                'Required parameter "polymarketSentimentRequest" was null or undefined when calling getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/prediction-market/polymarket/sentiment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PolymarketSentimentRequestToJSON(requestParameters['polymarketSentimentRequest']),
        };
    }

    /**
     * Get Polymarket Connector Sentiment
     */
    async getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRaw(requestParameters: GetPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolymarketSentimentResponse>> {
        const requestOptions = await this.getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolymarketSentimentResponseFromJSON(jsonValue));
    }

    /**
     * Get Polymarket Connector Sentiment
     */
    async getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPost(requestParameters: GetPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolymarketSentimentResponse> {
        const response = await this.getPolymarketConnectorSentimentApiPredictionMarketPolymarketSentimentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTopMoversApiSentimentMoversGet without sending the request
     */
    async getTopMoversApiSentimentMoversGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sentiment/movers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Top Movers
     */
    async getTopMoversApiSentimentMoversGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getTopMoversApiSentimentMoversGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Top Movers
     */
    async getTopMoversApiSentimentMoversGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getTopMoversApiSentimentMoversGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserNewsApiUserNewsPost without sending the request
     */
    async getUserNewsApiUserNewsPostRequestOpts(requestParameters: GetUserNewsApiUserNewsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userNewsRequest'] == null) {
            throw new runtime.RequiredError(
                'userNewsRequest',
                'Required parameter "userNewsRequest" was null or undefined when calling getUserNewsApiUserNewsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/user/news`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserNewsRequestToJSON(requestParameters['userNewsRequest']),
        };
    }

    /**
     * Fetch personalized news based on user\'s saved preferences in Supabase
     * Get User News
     */
    async getUserNewsApiUserNewsPostRaw(requestParameters: GetUserNewsApiUserNewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getUserNewsApiUserNewsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Fetch personalized news based on user\'s saved preferences in Supabase
     * Get User News
     */
    async getUserNewsApiUserNewsPost(requestParameters: GetUserNewsApiUserNewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getUserNewsApiUserNewsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWeatherAlertsApiWeatherAlertsGet without sending the request
     */
    async getWeatherAlertsApiWeatherAlertsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/alerts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Weather Alerts
     */
    async getWeatherAlertsApiWeatherAlertsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getWeatherAlertsApiWeatherAlertsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Weather Alerts
     */
    async getWeatherAlertsApiWeatherAlertsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getWeatherAlertsApiWeatherAlertsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthCheckHealthGet without sending the request
     */
    async healthCheckHealthGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Health Check
     */
    async healthCheckHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.healthCheckHealthGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health Check
     */
    async healthCheckHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.healthCheckHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGet without sending the request
     */
    async listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequestOpts(requestParameters: ListPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/prediction-market/connectors/polymarket/{user_id}`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Polymarket Connectors
     */
    async listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRaw(requestParameters: ListPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Polymarket Connectors
     */
    async listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGet(requestParameters: ListPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listPolymarketConnectorsApiPredictionMarketConnectorsPolymarketUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readRootGet without sending the request
     */
    async readRootGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read Root
     */
    async readRootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.readRootGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Read Root
     */
    async readRootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.readRootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for summarizeArticleApiSummarizeArticlePost without sending the request
     */
    async summarizeArticleApiSummarizeArticlePostRequestOpts(requestParameters: SummarizeArticleApiSummarizeArticlePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['articleSummarizeRequest'] == null) {
            throw new runtime.RequiredError(
                'articleSummarizeRequest',
                'Required parameter "articleSummarizeRequest" was null or undefined when calling summarizeArticleApiSummarizeArticlePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/summarize/article`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArticleSummarizeRequestToJSON(requestParameters['articleSummarizeRequest']),
        };
    }

    /**
     * Summarize a financial news article from URL
     * Summarize Article
     */
    async summarizeArticleApiSummarizeArticlePostRaw(requestParameters: SummarizeArticleApiSummarizeArticlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.summarizeArticleApiSummarizeArticlePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Summarize a financial news article from URL
     * Summarize Article
     */
    async summarizeArticleApiSummarizeArticlePost(requestParameters: SummarizeArticleApiSummarizeArticlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.summarizeArticleApiSummarizeArticlePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for testNewsEndpointApiTestNewsGet without sending the request
     */
    async testNewsEndpointApiTestNewsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/test/news`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Test endpoint for news functionality
     * Test News Endpoint
     */
    async testNewsEndpointApiTestNewsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.testNewsEndpointApiTestNewsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Test endpoint for news functionality
     * Test News Endpoint
     */
    async testNewsEndpointApiTestNewsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.testNewsEndpointApiTestNewsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePost without sending the request
     */
    async validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequestOpts(requestParameters: ValidatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['polymarketConnectorValidationRequest'] == null) {
            throw new runtime.RequiredError(
                'polymarketConnectorValidationRequest',
                'Required parameter "polymarketConnectorValidationRequest" was null or undefined when calling validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/prediction-market/connectors/polymarket/validate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PolymarketConnectorValidationRequestToJSON(requestParameters['polymarketConnectorValidationRequest']),
        };
    }

    /**
     * Validate Polymarket Connector
     */
    async validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRaw(requestParameters: ValidatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Validate Polymarket Connector
     */
    async validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePost(requestParameters: ValidatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.validatePolymarketConnectorApiPredictionMarketConnectorsPolymarketValidatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
