/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface GetDivergenceRequest {
    topics: string;
    threshold?: number;
    lookbackHours?: number;
    authorization?: string | null;
}

export interface GetDivergenceForTopicRequest {
    topic: string;
    threshold?: number;
    lookbackHours?: number;
    authorization?: string | null;
}

export interface ListTopicsRequest {
    authorization?: string | null;
}

/**
 * 
 */
export class DivergenceApi extends runtime.BaseAPI {

    /**
     * Creates request options for getDivergence without sending the request
     */
    async getDivergenceRequestOpts(requestParameters: GetDivergenceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['topics'] == null) {
            throw new runtime.RequiredError(
                'topics',
                'Required parameter "topics" was null or undefined when calling getDivergence().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['topics'] != null) {
            queryParameters['topics'] = requestParameters['topics'];
        }

        if (requestParameters['threshold'] != null) {
            queryParameters['threshold'] = requestParameters['threshold'];
        }

        if (requestParameters['lookbackHours'] != null) {
            queryParameters['lookback_hours'] = requestParameters['lookbackHours'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/markets/divergence`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Batch divergence — useful for the dashboard / scanner views.
     * Divergence Batch
     */
    async getDivergenceRaw(requestParameters: GetDivergenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getDivergenceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Batch divergence — useful for the dashboard / scanner views.
     * Divergence Batch
     */
    async getDivergence(requestParameters: GetDivergenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getDivergenceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDivergenceForTopic without sending the request
     */
    async getDivergenceForTopicRequestOpts(requestParameters: GetDivergenceForTopicRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['topic'] == null) {
            throw new runtime.RequiredError(
                'topic',
                'Required parameter "topic" was null or undefined when calling getDivergenceForTopic().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['threshold'] != null) {
            queryParameters['threshold'] = requestParameters['threshold'];
        }

        if (requestParameters['lookbackHours'] != null) {
            queryParameters['lookback_hours'] = requestParameters['lookbackHours'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/markets/divergence/{topic}`;
        urlPath = urlPath.replace('{topic}', encodeURIComponent(String(requestParameters['topic'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * News sentiment vs. prediction-market consensus for one topic.
     * Divergence For Topic
     */
    async getDivergenceForTopicRaw(requestParameters: GetDivergenceForTopicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getDivergenceForTopicRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * News sentiment vs. prediction-market consensus for one topic.
     * Divergence For Topic
     */
    async getDivergenceForTopic(requestParameters: GetDivergenceForTopicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getDivergenceForTopicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTopics without sending the request
     */
    async listTopicsRequestOpts(requestParameters: ListTopicsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/topics`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * All topics + categories Integra tracks for divergence.
     * List Topics
     */
    async listTopicsRaw(requestParameters: ListTopicsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.listTopicsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * All topics + categories Integra tracks for divergence.
     * List Topics
     */
    async listTopics(requestParameters: ListTopicsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.listTopicsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
