/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface ExportSentimentRequest {
    commodity: string;
    from?: string | null;
    to?: string | null;
    format?: string;
    authorization?: string | null;
}

/**
 * 
 */
export class ExportApi extends runtime.BaseAPI {

    /**
     * Creates request options for exportSentiment without sending the request
     */
    async exportSentimentRequestOpts(requestParameters: ExportSentimentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling exportSentiment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['commodity'] != null) {
            queryParameters['commodity'] = requestParameters['commodity'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/export/sentiment`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Bulk-export scored sentiment rows as CSV or XLSX.
     * Export Sentiment
     */
    async exportSentimentRaw(requestParameters: ExportSentimentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.exportSentimentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Bulk-export scored sentiment rows as CSV or XLSX.
     * Export Sentiment
     */
    async exportSentiment(requestParameters: ExportSentimentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.exportSentimentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
