/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface FindHistoricalAnalogsRequest {
    commodity: string;
    event: string;
    n?: number;
    authorization?: string | null;
}

export interface GetBriefRequest {
    commodity: string;
    authorization?: string | null;
}

export interface GetNarrativesRequest {
    commodity: string;
    lookback?: string;
    authorization?: string | null;
}

export interface GetSentimentRequest {
    commodity: string;
    window?: string;
    authorization?: string | null;
}

/**
 * 
 */
export class PublicV1Api extends runtime.BaseAPI {

    /**
     * Creates request options for findHistoricalAnalogs without sending the request
     */
    async findHistoricalAnalogsRequestOpts(requestParameters: FindHistoricalAnalogsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling findHistoricalAnalogs().'
            );
        }

        if (requestParameters['event'] == null) {
            throw new runtime.RequiredError(
                'event',
                'Required parameter "event" was null or undefined when calling findHistoricalAnalogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['commodity'] != null) {
            queryParameters['commodity'] = requestParameters['commodity'];
        }

        if (requestParameters['event'] != null) {
            queryParameters['event'] = requestParameters['event'];
        }

        if (requestParameters['n'] != null) {
            queryParameters['n'] = requestParameters['n'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/historical/analogs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Historical Analogs
     */
    async findHistoricalAnalogsRaw(requestParameters: FindHistoricalAnalogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.findHistoricalAnalogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Historical Analogs
     */
    async findHistoricalAnalogs(requestParameters: FindHistoricalAnalogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.findHistoricalAnalogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBrief without sending the request
     */
    async getBriefRequestOpts(requestParameters: GetBriefRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling getBrief().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['commodity'] != null) {
            queryParameters['commodity'] = requestParameters['commodity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/brief`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Composite briefing: 7d + 30d sentiment, top narratives, key divergences.  Composed from the same underlying data as the individual endpoints — one request instead of four so the MCP client can pull a full snapshot for Claude with minimum roundtrips.
     * Brief
     */
    async getBriefRaw(requestParameters: GetBriefRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getBriefRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Composite briefing: 7d + 30d sentiment, top narratives, key divergences.  Composed from the same underlying data as the individual endpoints — one request instead of four so the MCP client can pull a full snapshot for Claude with minimum roundtrips.
     * Brief
     */
    async getBrief(requestParameters: GetBriefRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getBriefRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNarratives without sending the request
     */
    async getNarrativesRequestOpts(requestParameters: GetNarrativesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling getNarratives().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['commodity'] != null) {
            queryParameters['commodity'] = requestParameters['commodity'];
        }

        if (requestParameters['lookback'] != null) {
            queryParameters['lookback'] = requestParameters['lookback'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/narratives`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Emerging themes derived from clustering recent article headlines.  Beta shape: groups articles by shared keyword stems in the headline and returns the top clusters with average sentiment. A dedicated topic-model service will replace this stem-clustering approach once we have training data volume to justify it.
     * Narratives
     */
    async getNarrativesRaw(requestParameters: GetNarrativesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getNarrativesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Emerging themes derived from clustering recent article headlines.  Beta shape: groups articles by shared keyword stems in the headline and returns the top clusters with average sentiment. A dedicated topic-model service will replace this stem-clustering approach once we have training data volume to justify it.
     * Narratives
     */
    async getNarratives(requestParameters: GetNarrativesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getNarrativesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSentiment without sending the request
     */
    async getSentimentRequestOpts(requestParameters: GetSentimentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling getSentiment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['commodity'] != null) {
            queryParameters['commodity'] = requestParameters['commodity'];
        }

        if (requestParameters['window'] != null) {
            queryParameters['window'] = requestParameters['window'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sentiment`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sentiment
     */
    async getSentimentRaw(requestParameters: GetSentimentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getSentimentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sentiment
     */
    async getSentiment(requestParameters: GetSentimentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getSentimentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
