/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface GetMarketOverlayRequest {
    provider?: string;
    status?: string;
    limit?: number;
    authorization?: string | null;
}

export interface GetSentimentDailyRequest {
    commodity: string;
    days?: number;
    authorization?: string | null;
}

export interface GetSentimentHistoryRequest {
    commodity: string;
    from?: string | null;
    to?: string | null;
    limit?: number;
    authorization?: string | null;
}

export interface GetSentimentNowRequest {
    commodity: string;
    authorization?: string | null;
}

export interface ListCommoditiesRequest {
    authorization?: string | null;
}

/**
 * 
 */
export class SentimentHistoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMarketOverlay without sending the request
     */
    async getMarketOverlayRequestOpts(requestParameters: GetMarketOverlayRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/markets/overlay`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resolved prediction markets with linked news-sentiment context.  For the beta this returns the resolved markets enriched with the average news sentiment over the market\'s lifetime. Full per-snapshot overlay arrives once the nightly aggregation job is wired up; this endpoint already returns the shape that job will populate.
     * Markets Overlay
     */
    async getMarketOverlayRaw(requestParameters: GetMarketOverlayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getMarketOverlayRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Resolved prediction markets with linked news-sentiment context.  For the beta this returns the resolved markets enriched with the average news sentiment over the market\'s lifetime. Full per-snapshot overlay arrives once the nightly aggregation job is wired up; this endpoint already returns the shape that job will populate.
     * Markets Overlay
     */
    async getMarketOverlay(requestParameters: GetMarketOverlayRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getMarketOverlayRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSentimentDaily without sending the request
     */
    async getSentimentDailyRequestOpts(requestParameters: GetSentimentDailyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling getSentimentDaily().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sentiment/{commodity}/daily`;
        urlPath = urlPath.replace('{commodity}', encodeURIComponent(String(requestParameters['commodity'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Daily aggregates for the last N days, computed on-the-fly.
     * Sentiment Daily
     */
    async getSentimentDailyRaw(requestParameters: GetSentimentDailyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getSentimentDailyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Daily aggregates for the last N days, computed on-the-fly.
     * Sentiment Daily
     */
    async getSentimentDaily(requestParameters: GetSentimentDailyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getSentimentDailyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSentimentHistory without sending the request
     */
    async getSentimentHistoryRequestOpts(requestParameters: GetSentimentHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling getSentimentHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sentiment/{commodity}/history`;
        urlPath = urlPath.replace('{commodity}', encodeURIComponent(String(requestParameters['commodity'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Time-series of individual scored documents for `commodity`.
     * Sentiment History
     */
    async getSentimentHistoryRaw(requestParameters: GetSentimentHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getSentimentHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Time-series of individual scored documents for `commodity`.
     * Sentiment History
     */
    async getSentimentHistory(requestParameters: GetSentimentHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getSentimentHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSentimentNow without sending the request
     */
    async getSentimentNowRequestOpts(requestParameters: GetSentimentNowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commodity'] == null) {
            throw new runtime.RequiredError(
                'commodity',
                'Required parameter "commodity" was null or undefined when calling getSentimentNow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sentiment/{commodity}/now`;
        urlPath = urlPath.replace('{commodity}', encodeURIComponent(String(requestParameters['commodity'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Most recent observed sentiment for `commodity` plus a 24h rolling stat.
     * Sentiment Now
     */
    async getSentimentNowRaw(requestParameters: GetSentimentNowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getSentimentNowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Most recent observed sentiment for `commodity` plus a 24h rolling stat.
     * Sentiment Now
     */
    async getSentimentNow(requestParameters: GetSentimentNowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getSentimentNowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCommodities without sending the request
     */
    async listCommoditiesRequestOpts(requestParameters: ListCommoditiesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/commodities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return distinct commodities that have at least one scored document.
     * List Commodities
     */
    async listCommoditiesRaw(requestParameters: ListCommoditiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.listCommoditiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Return distinct commodities that have at least one scored document.
     * List Commodities
     */
    async listCommodities(requestParameters: ListCommoditiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.listCommoditiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
