/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AIAnalysisRequest
 */
export interface AIAnalysisRequest {
    /**
     * Query for AI analysis
     * @type {string}
     * @memberof AIAnalysisRequest
     */
    query: string;
    /**
     * Specific commodity context
     * @type {string}
     * @memberof AIAnalysisRequest
     */
    commodity?: string | null;
    /**
     * Enable tool use
     * @type {boolean}
     * @memberof AIAnalysisRequest
     */
    useTools?: boolean;
    /**
     * Enable web search
     * @type {boolean}
     * @memberof AIAnalysisRequest
     */
    searchWeb?: boolean;
}

/**
 * Check if a given object implements the AIAnalysisRequest interface.
 */
export function instanceOfAIAnalysisRequest(value: object): value is AIAnalysisRequest {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function AIAnalysisRequestFromJSON(json: any): AIAnalysisRequest {
    return AIAnalysisRequestFromJSONTyped(json, false);
}

export function AIAnalysisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIAnalysisRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
        'useTools': json['use_tools'] == null ? undefined : json['use_tools'],
        'searchWeb': json['search_web'] == null ? undefined : json['search_web'],
    };
}

export function AIAnalysisRequestToJSON(json: any): AIAnalysisRequest {
    return AIAnalysisRequestToJSONTyped(json, false);
}

export function AIAnalysisRequestToJSONTyped(value?: AIAnalysisRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'commodity': value['commodity'],
        'use_tools': value['useTools'],
        'search_web': value['searchWeb'],
    };
}

