/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AIChatRequest
 */
export interface AIChatRequest {
    /**
     * Chat messages
     * @type {Array<{ [key: string]: string; }>}
     * @memberof AIChatRequest
     */
    messages: Array<{ [key: string]: string; }>;
    /**
     * Available tools to use
     * @type {Array<string>}
     * @memberof AIChatRequest
     */
    availableTools?: Array<string> | null;
    /**
     * Commodity context
     * @type {string}
     * @memberof AIChatRequest
     */
    commodity?: string | null;
    /**
     * Response mode
     * @type {string}
     * @memberof AIChatRequest
     */
    mode?: string | null;
}

/**
 * Check if a given object implements the AIChatRequest interface.
 */
export function instanceOfAIChatRequest(value: object): value is AIChatRequest {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function AIChatRequestFromJSON(json: any): AIChatRequest {
    return AIChatRequestFromJSONTyped(json, false);
}

export function AIChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'],
        'availableTools': json['available_tools'] == null ? undefined : json['available_tools'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function AIChatRequestToJSON(json: any): AIChatRequest {
    return AIChatRequestToJSONTyped(json, false);
}

export function AIChatRequestToJSONTyped(value?: AIChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': value['messages'],
        'available_tools': value['availableTools'],
        'commodity': value['commodity'],
        'mode': value['mode'],
    };
}

