/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleSummarizeRequest
 */
export interface ArticleSummarizeRequest {
    /**
     * URL of the article to summarize
     * @type {string}
     * @memberof ArticleSummarizeRequest
     */
    url: string;
    /**
     * Number of sentences in summary
     * @type {number}
     * @memberof ArticleSummarizeRequest
     */
    sentences?: number;
    /**
     * Specific commodity to focus on
     * @type {string}
     * @memberof ArticleSummarizeRequest
     */
    commodity?: string | null;
}

/**
 * Check if a given object implements the ArticleSummarizeRequest interface.
 */
export function instanceOfArticleSummarizeRequest(value: object): value is ArticleSummarizeRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ArticleSummarizeRequestFromJSON(json: any): ArticleSummarizeRequest {
    return ArticleSummarizeRequestFromJSONTyped(json, false);
}

export function ArticleSummarizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleSummarizeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'sentences': json['sentences'] == null ? undefined : json['sentences'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
    };
}

export function ArticleSummarizeRequestToJSON(json: any): ArticleSummarizeRequest {
    return ArticleSummarizeRequestToJSONTyped(json, false);
}

export function ArticleSummarizeRequestToJSONTyped(value?: ArticleSummarizeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'sentences': value['sentences'],
        'commodity': value['commodity'],
    };
}

