/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AskRequest
 */
export interface AskRequest {
    /**
     * Free-form NL question.
     * @type {string}
     * @memberof AskRequest
     */
    question?: string | null;
    /**
     * Named template; one of interpret_today/trend_30d/divergence_check.
     * @type {string}
     * @memberof AskRequest
     */
    template?: string | null;
    /**
     * Template variables (overrides defaults).
     * @type {object}
     * @memberof AskRequest
     */
    variables?: object | null;
    /**
     * Convenience: same as variables.commodity.
     * @type {string}
     * @memberof AskRequest
     */
    commodity?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AskRequest
     */
    maxToolCalls?: number;
}

/**
 * Check if a given object implements the AskRequest interface.
 */
export function instanceOfAskRequest(value: object): value is AskRequest {
    return true;
}

export function AskRequestFromJSON(json: any): AskRequest {
    return AskRequestFromJSONTyped(json, false);
}

export function AskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'question': json['question'] == null ? undefined : json['question'],
        'template': json['template'] == null ? undefined : json['template'],
        'variables': json['variables'] == null ? undefined : json['variables'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
        'maxToolCalls': json['max_tool_calls'] == null ? undefined : json['max_tool_calls'],
    };
}

export function AskRequestToJSON(json: any): AskRequest {
    return AskRequestToJSONTyped(json, false);
}

export function AskRequestToJSONTyped(value?: AskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question': value['question'],
        'template': value['template'],
        'variables': value['variables'],
        'commodity': value['commodity'],
        'max_tool_calls': value['maxToolCalls'],
    };
}

