/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AskResponse
 */
export interface AskResponse {
    /**
     * 
     * @type {string}
     * @memberof AskResponse
     */
    answer: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof AskResponse
     */
    sources: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof AskResponse
     */
    toolCalls: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof AskResponse
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof AskResponse
     */
    templateUsed?: string | null;
}

/**
 * Check if a given object implements the AskResponse interface.
 */
export function instanceOfAskResponse(value: object): value is AskResponse {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    if (!('toolCalls' in value) || value['toolCalls'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function AskResponseFromJSON(json: any): AskResponse {
    return AskResponseFromJSONTyped(json, false);
}

export function AskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'sources': json['sources'],
        'toolCalls': json['tool_calls'],
        'model': json['model'],
        'templateUsed': json['template_used'] == null ? undefined : json['template_used'],
    };
}

export function AskResponseToJSON(json: any): AskResponse {
    return AskResponseToJSONTyped(json, false);
}

export function AskResponseToJSONTyped(value?: AskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'sources': value['sources'],
        'tool_calls': value['toolCalls'],
        'model': value['model'],
        'template_used': value['templateUsed'],
    };
}

