/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectorCredentialRequest
 */
export interface ConnectorCredentialRequest {
    /**
     * Credential mode: none, api_key, or bearer
     * @type {string}
     * @memberof ConnectorCredentialRequest
     */
    authType?: string;
    /**
     * User-provided API key or subscription token
     * @type {string}
     * @memberof ConnectorCredentialRequest
     */
    apiKey?: string | null;
    /**
     * User-provided bearer token
     * @type {string}
     * @memberof ConnectorCredentialRequest
     */
    bearerToken?: string | null;
    /**
     * Header name used when auth_type is api_key
     * @type {string}
     * @memberof ConnectorCredentialRequest
     */
    apiKeyHeader?: string | null;
    /**
     * Store the credential encrypted for future connector runs
     * @type {boolean}
     * @memberof ConnectorCredentialRequest
     */
    persistSecret?: boolean;
}

/**
 * Check if a given object implements the ConnectorCredentialRequest interface.
 */
export function instanceOfConnectorCredentialRequest(value: object): value is ConnectorCredentialRequest {
    return true;
}

export function ConnectorCredentialRequestFromJSON(json: any): ConnectorCredentialRequest {
    return ConnectorCredentialRequestFromJSONTyped(json, false);
}

export function ConnectorCredentialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorCredentialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'authType': json['auth_type'] == null ? undefined : json['auth_type'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'bearerToken': json['bearer_token'] == null ? undefined : json['bearer_token'],
        'apiKeyHeader': json['api_key_header'] == null ? undefined : json['api_key_header'],
        'persistSecret': json['persist_secret'] == null ? undefined : json['persist_secret'],
    };
}

export function ConnectorCredentialRequestToJSON(json: any): ConnectorCredentialRequest {
    return ConnectorCredentialRequestToJSONTyped(json, false);
}

export function ConnectorCredentialRequestToJSONTyped(value?: ConnectorCredentialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_type': value['authType'],
        'api_key': value['apiKey'],
        'bearer_token': value['bearerToken'],
        'api_key_header': value['apiKeyHeader'],
        'persist_secret': value['persistSecret'],
    };
}

