/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateKeyResponse
 */
export interface CreateKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    prefix: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKeyResponse
     */
    createdAt: string;
}

/**
 * Check if a given object implements the CreateKeyResponse interface.
 */
export function instanceOfCreateKeyResponse(value: object): value is CreateKeyResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreateKeyResponseFromJSON(json: any): CreateKeyResponse {
    return CreateKeyResponseFromJSONTyped(json, false);
}

export function CreateKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'key': json['key'],
        'prefix': json['prefix'],
        'name': json['name'],
        'createdAt': json['created_at'],
    };
}

export function CreateKeyResponseToJSON(json: any): CreateKeyResponse {
    return CreateKeyResponseToJSONTyped(json, false);
}

export function CreateKeyResponseToJSONTyped(value?: CreateKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'prefix': value['prefix'],
        'name': value['name'],
        'created_at': value['createdAt'],
    };
}

