/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardSentimentEngineRequest
 */
export interface DashboardSentimentEngineRequest {
    /**
     * Tracked commodities to include in the dashboard snapshot
     * @type {Array<string>}
     * @memberof DashboardSentimentEngineRequest
     */
    commodities?: Array<string> | null;
    /**
     * Maximum headlines per commodity snapshot
     * @type {number}
     * @memberof DashboardSentimentEngineRequest
     */
    maxHeadlines?: number;
    /**
     * Fetch headlines if the dashboard cache is empty
     * @type {boolean}
     * @memberof DashboardSentimentEngineRequest
     */
    refreshIfEmpty?: boolean;
}

/**
 * Check if a given object implements the DashboardSentimentEngineRequest interface.
 */
export function instanceOfDashboardSentimentEngineRequest(value: object): value is DashboardSentimentEngineRequest {
    return true;
}

export function DashboardSentimentEngineRequestFromJSON(json: any): DashboardSentimentEngineRequest {
    return DashboardSentimentEngineRequestFromJSONTyped(json, false);
}

export function DashboardSentimentEngineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardSentimentEngineRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'commodities': json['commodities'] == null ? undefined : json['commodities'],
        'maxHeadlines': json['max_headlines'] == null ? undefined : json['max_headlines'],
        'refreshIfEmpty': json['refresh_if_empty'] == null ? undefined : json['refresh_if_empty'],
    };
}

export function DashboardSentimentEngineRequestToJSON(json: any): DashboardSentimentEngineRequest {
    return DashboardSentimentEngineRequestToJSONTyped(json, false);
}

export function DashboardSentimentEngineRequestToJSONTyped(value?: DashboardSentimentEngineRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commodities': value['commodities'],
        'max_headlines': value['maxHeadlines'],
        'refresh_if_empty': value['refreshIfEmpty'],
    };
}

