/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyRow
 */
export interface KeyRow {
    /**
     * 
     * @type {string}
     * @memberof KeyRow
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof KeyRow
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof KeyRow
     */
    prefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KeyRow
     */
    scopes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KeyRow
     */
    lastUsedAt: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyRow
     */
    createdAt: string;
}

/**
 * Check if a given object implements the KeyRow interface.
 */
export function instanceOfKeyRow(value: object): value is KeyRow {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    if (!('lastUsedAt' in value) || value['lastUsedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function KeyRowFromJSON(json: any): KeyRow {
    return KeyRowFromJSONTyped(json, false);
}

export function KeyRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyRow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'prefix': json['prefix'],
        'scopes': json['scopes'],
        'lastUsedAt': json['last_used_at'],
        'createdAt': json['created_at'],
    };
}

export function KeyRowToJSON(json: any): KeyRow {
    return KeyRowToJSONTyped(json, false);
}

export function KeyRowToJSONTyped(value?: KeyRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'prefix': value['prefix'],
        'scopes': value['scopes'],
        'last_used_at': value['lastUsedAt'],
        'created_at': value['createdAt'],
    };
}

