/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LexiconExplainRequest
 */
export interface LexiconExplainRequest {
    /**
     * Text to analyze with the commodity lexicon
     * @type {string}
     * @memberof LexiconExplainRequest
     */
    text: string;
    /**
     * Commodity context to force during analysis
     * @type {string}
     * @memberof LexiconExplainRequest
     */
    commodity?: string | null;
    /**
     * Include the underlying commodity rulebook in the response
     * @type {boolean}
     * @memberof LexiconExplainRequest
     */
    includeRulebook?: boolean;
}

/**
 * Check if a given object implements the LexiconExplainRequest interface.
 */
export function instanceOfLexiconExplainRequest(value: object): value is LexiconExplainRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function LexiconExplainRequestFromJSON(json: any): LexiconExplainRequest {
    return LexiconExplainRequestFromJSONTyped(json, false);
}

export function LexiconExplainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LexiconExplainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
        'includeRulebook': json['include_rulebook'] == null ? undefined : json['include_rulebook'],
    };
}

export function LexiconExplainRequestToJSON(json: any): LexiconExplainRequest {
    return LexiconExplainRequestToJSONTyped(json, false);
}

export function LexiconExplainRequestToJSONTyped(value?: LexiconExplainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'commodity': value['commodity'],
        'include_rulebook': value['includeRulebook'],
    };
}

