/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewsRequest
 */
export interface NewsRequest {
    /**
     * Maximum number of articles to return
     * @type {number}
     * @memberof NewsRequest
     */
    maxArticles?: number | null;
    /**
     * Specific news sources to fetch from
     * @type {Array<string>}
     * @memberof NewsRequest
     */
    sources?: Array<string> | null;
    /**
     * Filter for specific commodity
     * @type {string}
     * @memberof NewsRequest
     */
    commodityFilter?: string | null;
    /**
     * Hours back to fetch news from
     * @type {number}
     * @memberof NewsRequest
     */
    hoursBack?: number | null;
    /**
     * Enable full HTML content extraction and NLTK summarization
     * @type {boolean}
     * @memberof NewsRequest
     */
    enhancedContent?: boolean | null;
    /**
     * Maximum number of articles to enhance with full content
     * @type {number}
     * @memberof NewsRequest
     */
    maxEnhanced?: number | null;
    /**
     * Alert frequency preference (realtime, daily, weekly)
     * @type {string}
     * @memberof NewsRequest
     */
    alertFrequency?: string | null;
    /**
     * Minimum impact level for alerts (LOW, MEDIUM, HIGH)
     * @type {string}
     * @memberof NewsRequest
     */
    minImpact?: string | null;
}

/**
 * Check if a given object implements the NewsRequest interface.
 */
export function instanceOfNewsRequest(value: object): value is NewsRequest {
    return true;
}

export function NewsRequestFromJSON(json: any): NewsRequest {
    return NewsRequestFromJSONTyped(json, false);
}

export function NewsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'maxArticles': json['max_articles'] == null ? undefined : json['max_articles'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'commodityFilter': json['commodity_filter'] == null ? undefined : json['commodity_filter'],
        'hoursBack': json['hours_back'] == null ? undefined : json['hours_back'],
        'enhancedContent': json['enhanced_content'] == null ? undefined : json['enhanced_content'],
        'maxEnhanced': json['max_enhanced'] == null ? undefined : json['max_enhanced'],
        'alertFrequency': json['alert_frequency'] == null ? undefined : json['alert_frequency'],
        'minImpact': json['min_impact'] == null ? undefined : json['min_impact'],
    };
}

export function NewsRequestToJSON(json: any): NewsRequest {
    return NewsRequestToJSONTyped(json, false);
}

export function NewsRequestToJSONTyped(value?: NewsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_articles': value['maxArticles'],
        'sources': value['sources'],
        'commodity_filter': value['commodityFilter'],
        'hours_back': value['hoursBack'],
        'enhanced_content': value['enhancedContent'],
        'max_enhanced': value['maxEnhanced'],
        'alert_frequency': value['alertFrequency'],
        'min_impact': value['minImpact'],
    };
}

