/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewsAnalysisRequest
 */
export interface NewsAnalysisRequest {
    /**
     * 
     * @type {string}
     * @memberof NewsAnalysisRequest
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof NewsAnalysisRequest
     */
    source?: string | null;
}

/**
 * Check if a given object implements the NewsAnalysisRequest interface.
 */
export function instanceOfNewsAnalysisRequest(value: object): value is NewsAnalysisRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function NewsAnalysisRequestFromJSON(json: any): NewsAnalysisRequest {
    return NewsAnalysisRequestFromJSONTyped(json, false);
}

export function NewsAnalysisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsAnalysisRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function NewsAnalysisRequestToJSON(json: any): NewsAnalysisRequest {
    return NewsAnalysisRequestToJSONTyped(json, false);
}

export function NewsAnalysisRequestToJSONTyped(value?: NewsAnalysisRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'source': value['source'],
    };
}

