/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverallSentimentRequest
 */
export interface OverallSentimentRequest {
    /**
     * Market topic or question to score against recent headlines
     * @type {string}
     * @memberof OverallSentimentRequest
     */
    topicText: string;
    /**
     * Optional commodity override
     * @type {string}
     * @memberof OverallSentimentRequest
     */
    commodity?: string | null;
    /**
     * Maximum recent headlines to include
     * @type {number}
     * @memberof OverallSentimentRequest
     */
    maxHeadlines?: number;
    /**
     * Fetch the latest feed if the recent-headlines cache is empty
     * @type {boolean}
     * @memberof OverallSentimentRequest
     */
    refreshIfEmpty?: boolean;
    /**
     * Canonical Polymarket event URL for event-driven analysis
     * @type {string}
     * @memberof OverallSentimentRequest
     */
    eventUrl?: string | null;
    /**
     * Canonical Polymarket event slug
     * @type {string}
     * @memberof OverallSentimentRequest
     */
    eventSlug?: string | null;
}

/**
 * Check if a given object implements the OverallSentimentRequest interface.
 */
export function instanceOfOverallSentimentRequest(value: object): value is OverallSentimentRequest {
    if (!('topicText' in value) || value['topicText'] === undefined) return false;
    return true;
}

export function OverallSentimentRequestFromJSON(json: any): OverallSentimentRequest {
    return OverallSentimentRequestFromJSONTyped(json, false);
}

export function OverallSentimentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverallSentimentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'topicText': json['topic_text'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
        'maxHeadlines': json['max_headlines'] == null ? undefined : json['max_headlines'],
        'refreshIfEmpty': json['refresh_if_empty'] == null ? undefined : json['refresh_if_empty'],
        'eventUrl': json['event_url'] == null ? undefined : json['event_url'],
        'eventSlug': json['event_slug'] == null ? undefined : json['event_slug'],
    };
}

export function OverallSentimentRequestToJSON(json: any): OverallSentimentRequest {
    return OverallSentimentRequestToJSONTyped(json, false);
}

export function OverallSentimentRequestToJSONTyped(value?: OverallSentimentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topic_text': value['topicText'],
        'commodity': value['commodity'],
        'max_headlines': value['maxHeadlines'],
        'refresh_if_empty': value['refreshIfEmpty'],
        'event_url': value['eventUrl'],
        'event_slug': value['eventSlug'],
    };
}

