/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectorCredentialRequest } from './ConnectorCredentialRequest';
import {
    ConnectorCredentialRequestFromJSON,
    ConnectorCredentialRequestFromJSONTyped,
    ConnectorCredentialRequestToJSON,
    ConnectorCredentialRequestToJSONTyped,
} from './ConnectorCredentialRequest';

/**
 * 
 * @export
 * @interface PolymarketConnectorRequest
 */
export interface PolymarketConnectorRequest {
    /**
     * Owning user ID
     * @type {string}
     * @memberof PolymarketConnectorRequest
     */
    userId: string;
    /**
     * User-visible connector name
     * @type {string}
     * @memberof PolymarketConnectorRequest
     */
    name: string;
    /**
     * shared, hybrid, or tenant_private
     * @type {string}
     * @memberof PolymarketConnectorRequest
     */
    sourceMode?: string;
    /**
     * Base endpoint or portal URL for the connector
     * @type {string}
     * @memberof PolymarketConnectorRequest
     */
    baseUrl?: string | null;
    /**
     * Optional canonical Polymarket event URL
     * @type {string}
     * @memberof PolymarketConnectorRequest
     */
    eventUrl?: string | null;
    /**
     * Optional Polymarket event slug
     * @type {string}
     * @memberof PolymarketConnectorRequest
     */
    eventSlug?: string | null;
    /**
     * Optional user-owned source URLs
     * @type {Array<string>}
     * @memberof PolymarketConnectorRequest
     */
    websiteUrls?: Array<string> | null;
    /**
     * Additional pass-through headers
     * @type {{ [key: string]: string; }}
     * @memberof PolymarketConnectorRequest
     */
    customHeaders?: { [key: string]: string; } | null;
    /**
     * Whether this connector should use the user's own vendor credentials
     * @type {boolean}
     * @memberof PolymarketConnectorRequest
     */
    usePersonalSubscription?: boolean;
    /**
     * Whether requests should avoid shared platform source pools
     * @type {boolean}
     * @memberof PolymarketConnectorRequest
     */
    bypassSharedLimits?: boolean;
    /**
     * Tenant-specific limit for this connector
     * @type {number}
     * @memberof PolymarketConnectorRequest
     */
    rateLimitPerMinute?: number | null;
    /**
     * Connector-local cache TTL
     * @type {number}
     * @memberof PolymarketConnectorRequest
     */
    cacheTtlSeconds?: number;
    /**
     * Optional BYO credential payload
     * @type {ConnectorCredentialRequest}
     * @memberof PolymarketConnectorRequest
     */
    credentials?: ConnectorCredentialRequest | null;
}

/**
 * Check if a given object implements the PolymarketConnectorRequest interface.
 */
export function instanceOfPolymarketConnectorRequest(value: object): value is PolymarketConnectorRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PolymarketConnectorRequestFromJSON(json: any): PolymarketConnectorRequest {
    return PolymarketConnectorRequestFromJSONTyped(json, false);
}

export function PolymarketConnectorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolymarketConnectorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'name': json['name'],
        'sourceMode': json['source_mode'] == null ? undefined : json['source_mode'],
        'baseUrl': json['base_url'] == null ? undefined : json['base_url'],
        'eventUrl': json['event_url'] == null ? undefined : json['event_url'],
        'eventSlug': json['event_slug'] == null ? undefined : json['event_slug'],
        'websiteUrls': json['website_urls'] == null ? undefined : json['website_urls'],
        'customHeaders': json['custom_headers'] == null ? undefined : json['custom_headers'],
        'usePersonalSubscription': json['use_personal_subscription'] == null ? undefined : json['use_personal_subscription'],
        'bypassSharedLimits': json['bypass_shared_limits'] == null ? undefined : json['bypass_shared_limits'],
        'rateLimitPerMinute': json['rate_limit_per_minute'] == null ? undefined : json['rate_limit_per_minute'],
        'cacheTtlSeconds': json['cache_ttl_seconds'] == null ? undefined : json['cache_ttl_seconds'],
        'credentials': json['credentials'] == null ? undefined : ConnectorCredentialRequestFromJSON(json['credentials']),
    };
}

export function PolymarketConnectorRequestToJSON(json: any): PolymarketConnectorRequest {
    return PolymarketConnectorRequestToJSONTyped(json, false);
}

export function PolymarketConnectorRequestToJSONTyped(value?: PolymarketConnectorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'name': value['name'],
        'source_mode': value['sourceMode'],
        'base_url': value['baseUrl'],
        'event_url': value['eventUrl'],
        'event_slug': value['eventSlug'],
        'website_urls': value['websiteUrls'],
        'custom_headers': value['customHeaders'],
        'use_personal_subscription': value['usePersonalSubscription'],
        'bypass_shared_limits': value['bypassSharedLimits'],
        'rate_limit_per_minute': value['rateLimitPerMinute'],
        'cache_ttl_seconds': value['cacheTtlSeconds'],
        'credentials': ConnectorCredentialRequestToJSON(value['credentials']),
    };
}

