/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SentimentBreakdown } from './SentimentBreakdown';
import {
    SentimentBreakdownFromJSON,
    SentimentBreakdownFromJSONTyped,
    SentimentBreakdownToJSON,
    SentimentBreakdownToJSONTyped,
} from './SentimentBreakdown';
import type { PolymarketConnectorContext } from './PolymarketConnectorContext';
import {
    PolymarketConnectorContextFromJSON,
    PolymarketConnectorContextFromJSONTyped,
    PolymarketConnectorContextToJSON,
    PolymarketConnectorContextToJSONTyped,
} from './PolymarketConnectorContext';

/**
 * 
 * @export
 * @interface PolymarketSentimentResponse
 */
export interface PolymarketSentimentResponse {
    /**
     * Echo of the original request topic
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    topicText: string;
    /**
     * Canonical asset key (internal)
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    primaryTarget?: string | null;
    /**
     * Commodity key, alias of primary_target
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    commodity?: string | null;
    /**
     * Title-cased commodity name for UI
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    displayName?: string | null;
    /**
     * All inferred asset symbols (uppercase)
     * @type {Array<string>}
     * @memberof PolymarketSentimentResponse
     */
    targetAssets?: Array<string>;
    /**
     * One of BULLISH, BEARISH, NEUTRAL
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    overallSentiment: string;
    /**
     * Confidence in the overall classification
     * @type {number}
     * @memberof PolymarketSentimentResponse
     */
    confidence: number;
    /**
     * Number of relevant headlines used
     * @type {number}
     * @memberof PolymarketSentimentResponse
     */
    headlineCount?: number;
    /**
     * Human-readable aggregate summary
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    summary: string;
    /**
     * 
     * @type {SentimentBreakdown}
     * @memberof PolymarketSentimentResponse
     */
    sentimentBreakdown?: SentimentBreakdown;
    /**
     * Up to 5 representative headlines
     * @type {Array<string>}
     * @memberof PolymarketSentimentResponse
     */
    sampleHeadlines?: Array<string>;
    /**
     * Up to 5 keyword features driving the score
     * @type {Array<string>}
     * @memberof PolymarketSentimentResponse
     */
    matchedSignals?: Array<string>;
    /**
     * Identifier of the analyzer used
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    method?: string;
    /**
     * Canonical Polymarket event URL
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    eventUrl?: string | null;
    /**
     * Canonical Polymarket event slug
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    eventSlug?: string | null;
    /**
     * Canonical source URL (mirrors event_url)
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    sourceUrl?: string | null;
    /**
     * ISO timestamp of the headline cache snapshot
     * @type {string}
     * @memberof PolymarketSentimentResponse
     */
    cacheTimestamp?: string | null;
    /**
     * Connector / auth provenance for this response
     * @type {PolymarketConnectorContext}
     * @memberof PolymarketSentimentResponse
     */
    connectorContext?: PolymarketConnectorContext | null;
}

/**
 * Check if a given object implements the PolymarketSentimentResponse interface.
 */
export function instanceOfPolymarketSentimentResponse(value: object): value is PolymarketSentimentResponse {
    if (!('topicText' in value) || value['topicText'] === undefined) return false;
    if (!('overallSentiment' in value) || value['overallSentiment'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function PolymarketSentimentResponseFromJSON(json: any): PolymarketSentimentResponse {
    return PolymarketSentimentResponseFromJSONTyped(json, false);
}

export function PolymarketSentimentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolymarketSentimentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'topicText': json['topic_text'],
        'primaryTarget': json['primary_target'] == null ? undefined : json['primary_target'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'targetAssets': json['target_assets'] == null ? undefined : json['target_assets'],
        'overallSentiment': json['overall_sentiment'],
        'confidence': json['confidence'],
        'headlineCount': json['headline_count'] == null ? undefined : json['headline_count'],
        'summary': json['summary'],
        'sentimentBreakdown': json['sentiment_breakdown'] == null ? undefined : SentimentBreakdownFromJSON(json['sentiment_breakdown']),
        'sampleHeadlines': json['sample_headlines'] == null ? undefined : json['sample_headlines'],
        'matchedSignals': json['matched_signals'] == null ? undefined : json['matched_signals'],
        'method': json['method'] == null ? undefined : json['method'],
        'eventUrl': json['event_url'] == null ? undefined : json['event_url'],
        'eventSlug': json['event_slug'] == null ? undefined : json['event_slug'],
        'sourceUrl': json['source_url'] == null ? undefined : json['source_url'],
        'cacheTimestamp': json['cache_timestamp'] == null ? undefined : json['cache_timestamp'],
        'connectorContext': json['connector_context'] == null ? undefined : PolymarketConnectorContextFromJSON(json['connector_context']),
    };
}

export function PolymarketSentimentResponseToJSON(json: any): PolymarketSentimentResponse {
    return PolymarketSentimentResponseToJSONTyped(json, false);
}

export function PolymarketSentimentResponseToJSONTyped(value?: PolymarketSentimentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topic_text': value['topicText'],
        'primary_target': value['primaryTarget'],
        'commodity': value['commodity'],
        'display_name': value['displayName'],
        'target_assets': value['targetAssets'],
        'overall_sentiment': value['overallSentiment'],
        'confidence': value['confidence'],
        'headline_count': value['headlineCount'],
        'summary': value['summary'],
        'sentiment_breakdown': SentimentBreakdownToJSON(value['sentimentBreakdown']),
        'sample_headlines': value['sampleHeadlines'],
        'matched_signals': value['matchedSignals'],
        'method': value['method'],
        'event_url': value['eventUrl'],
        'event_slug': value['eventSlug'],
        'source_url': value['sourceUrl'],
        'cache_timestamp': value['cacheTimestamp'],
        'connector_context': PolymarketConnectorContextToJSON(value['connectorContext']),
    };
}

