/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolymarketConnectorRequest } from './PolymarketConnectorRequest';
import {
    PolymarketConnectorRequestFromJSON,
    PolymarketConnectorRequestFromJSONTyped,
    PolymarketConnectorRequestToJSON,
    PolymarketConnectorRequestToJSONTyped,
} from './PolymarketConnectorRequest';

/**
 * 
 * @export
 * @interface PolymarketConnectorValidationRequest
 */
export interface PolymarketConnectorValidationRequest {
    /**
     * 
     * @type {PolymarketConnectorRequest}
     * @memberof PolymarketConnectorValidationRequest
     */
    connector: PolymarketConnectorRequest;
}

/**
 * Check if a given object implements the PolymarketConnectorValidationRequest interface.
 */
export function instanceOfPolymarketConnectorValidationRequest(value: object): value is PolymarketConnectorValidationRequest {
    if (!('connector' in value) || value['connector'] === undefined) return false;
    return true;
}

export function PolymarketConnectorValidationRequestFromJSON(json: any): PolymarketConnectorValidationRequest {
    return PolymarketConnectorValidationRequestFromJSONTyped(json, false);
}

export function PolymarketConnectorValidationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolymarketConnectorValidationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'connector': PolymarketConnectorRequestFromJSON(json['connector']),
    };
}

export function PolymarketConnectorValidationRequestToJSON(json: any): PolymarketConnectorValidationRequest {
    return PolymarketConnectorValidationRequestToJSONTyped(json, false);
}

export function PolymarketConnectorValidationRequestToJSONTyped(value?: PolymarketConnectorValidationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connector': PolymarketConnectorRequestToJSON(value['connector']),
    };
}

