/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolymarketConnectorAuthSummary
 */
export interface PolymarketConnectorAuthSummary {
    /**
     * Credential mode: none, api_key, or bearer
     * @type {string}
     * @memberof PolymarketConnectorAuthSummary
     */
    authType?: string | null;
    /**
     * Header name when auth_type is api_key
     * @type {string}
     * @memberof PolymarketConnectorAuthSummary
     */
    apiKeyHeader?: string | null;
    /**
     * Whether a credential is present
     * @type {boolean}
     * @memberof PolymarketConnectorAuthSummary
     */
    hasSecret?: boolean;
    /**
     * Masked preview of the credential
     * @type {string}
     * @memberof PolymarketConnectorAuthSummary
     */
    maskedSecret?: string | null;
    /**
     * Whether the credential is stored for reuse
     * @type {boolean}
     * @memberof PolymarketConnectorAuthSummary
     */
    persisted?: boolean | null;
}

/**
 * Check if a given object implements the PolymarketConnectorAuthSummary interface.
 */
export function instanceOfPolymarketConnectorAuthSummary(value: object): value is PolymarketConnectorAuthSummary {
    return true;
}

export function PolymarketConnectorAuthSummaryFromJSON(json: any): PolymarketConnectorAuthSummary {
    return PolymarketConnectorAuthSummaryFromJSONTyped(json, false);
}

export function PolymarketConnectorAuthSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolymarketConnectorAuthSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'authType': json['auth_type'] == null ? undefined : json['auth_type'],
        'apiKeyHeader': json['api_key_header'] == null ? undefined : json['api_key_header'],
        'hasSecret': json['has_secret'] == null ? undefined : json['has_secret'],
        'maskedSecret': json['masked_secret'] == null ? undefined : json['masked_secret'],
        'persisted': json['persisted'] == null ? undefined : json['persisted'],
    };
}

export function PolymarketConnectorAuthSummaryToJSON(json: any): PolymarketConnectorAuthSummary {
    return PolymarketConnectorAuthSummaryToJSONTyped(json, false);
}

export function PolymarketConnectorAuthSummaryToJSONTyped(value?: PolymarketConnectorAuthSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_type': value['authType'],
        'api_key_header': value['apiKeyHeader'],
        'has_secret': value['hasSecret'],
        'masked_secret': value['maskedSecret'],
        'persisted': value['persisted'],
    };
}

