/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolymarketAuthenticationMeta } from './PolymarketAuthenticationMeta';
import {
    PolymarketAuthenticationMetaFromJSON,
    PolymarketAuthenticationMetaFromJSONTyped,
    PolymarketAuthenticationMetaToJSON,
    PolymarketAuthenticationMetaToJSONTyped,
} from './PolymarketAuthenticationMeta';
import type { PolymarketConnectorAuthSummary } from './PolymarketConnectorAuthSummary';
import {
    PolymarketConnectorAuthSummaryFromJSON,
    PolymarketConnectorAuthSummaryFromJSONTyped,
    PolymarketConnectorAuthSummaryToJSON,
    PolymarketConnectorAuthSummaryToJSONTyped,
} from './PolymarketConnectorAuthSummary';

/**
 * 
 * @export
 * @interface PolymarketConnectorContext
 */
export interface PolymarketConnectorContext {
    /**
     * Saved connector ID, if any
     * @type {string}
     * @memberof PolymarketConnectorContext
     */
    connectorId?: string | null;
    /**
     * shared, hybrid, or tenant_private
     * @type {string}
     * @memberof PolymarketConnectorContext
     */
    sourceMode?: string;
    /**
     * True when this request used the user's own credential
     * @type {boolean}
     * @memberof PolymarketConnectorContext
     */
    usesPersonalSubscription?: boolean;
    /**
     * True when this request avoided shared rate limits
     * @type {boolean}
     * @memberof PolymarketConnectorContext
     */
    bypassSharedLimits?: boolean;
    /**
     * 
     * @type {PolymarketConnectorAuthSummary}
     * @memberof PolymarketConnectorContext
     */
    auth?: PolymarketConnectorAuthSummary;
    /**
     * 
     * @type {PolymarketAuthenticationMeta}
     * @memberof PolymarketConnectorContext
     */
    authentication?: PolymarketAuthenticationMeta;
}

/**
 * Check if a given object implements the PolymarketConnectorContext interface.
 */
export function instanceOfPolymarketConnectorContext(value: object): value is PolymarketConnectorContext {
    return true;
}

export function PolymarketConnectorContextFromJSON(json: any): PolymarketConnectorContext {
    return PolymarketConnectorContextFromJSONTyped(json, false);
}

export function PolymarketConnectorContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolymarketConnectorContext {
    if (json == null) {
        return json;
    }
    return {
        
        'connectorId': json['connector_id'] == null ? undefined : json['connector_id'],
        'sourceMode': json['source_mode'] == null ? undefined : json['source_mode'],
        'usesPersonalSubscription': json['uses_personal_subscription'] == null ? undefined : json['uses_personal_subscription'],
        'bypassSharedLimits': json['bypass_shared_limits'] == null ? undefined : json['bypass_shared_limits'],
        'auth': json['auth'] == null ? undefined : PolymarketConnectorAuthSummaryFromJSON(json['auth']),
        'authentication': json['authentication'] == null ? undefined : PolymarketAuthenticationMetaFromJSON(json['authentication']),
    };
}

export function PolymarketConnectorContextToJSON(json: any): PolymarketConnectorContext {
    return PolymarketConnectorContextToJSONTyped(json, false);
}

export function PolymarketConnectorContextToJSONTyped(value?: PolymarketConnectorContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connector_id': value['connectorId'],
        'source_mode': value['sourceMode'],
        'uses_personal_subscription': value['usesPersonalSubscription'],
        'bypass_shared_limits': value['bypassSharedLimits'],
        'auth': PolymarketConnectorAuthSummaryToJSON(value['auth']),
        'authentication': PolymarketAuthenticationMetaToJSON(value['authentication']),
    };
}

