/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectorCredentialRequest } from './ConnectorCredentialRequest';
import {
    ConnectorCredentialRequestFromJSON,
    ConnectorCredentialRequestFromJSONTyped,
    ConnectorCredentialRequestToJSON,
    ConnectorCredentialRequestToJSONTyped,
} from './ConnectorCredentialRequest';

/**
 * 
 * @export
 * @interface PolymarketSentimentRequest
 */
export interface PolymarketSentimentRequest {
    /**
     * Market topic or question to score
     * @type {string}
     * @memberof PolymarketSentimentRequest
     */
    topicText: string;
    /**
     * Optional owning user ID when resolving a saved connector
     * @type {string}
     * @memberof PolymarketSentimentRequest
     */
    userId?: string | null;
    /**
     * Optional saved Polymarket connector ID
     * @type {string}
     * @memberof PolymarketSentimentRequest
     */
    connectorId?: string | null;
    /**
     * Canonical Polymarket event URL
     * @type {string}
     * @memberof PolymarketSentimentRequest
     */
    eventUrl?: string | null;
    /**
     * Canonical Polymarket event slug
     * @type {string}
     * @memberof PolymarketSentimentRequest
     */
    eventSlug?: string | null;
    /**
     * Maximum headlines to include
     * @type {number}
     * @memberof PolymarketSentimentRequest
     */
    maxHeadlines?: number;
    /**
     * Fetch headlines if cache is empty
     * @type {boolean}
     * @memberof PolymarketSentimentRequest
     */
    refreshIfEmpty?: boolean;
    /**
     * Optional one-off BYO credential without saving
     * @type {ConnectorCredentialRequest}
     * @memberof PolymarketSentimentRequest
     */
    credentials?: ConnectorCredentialRequest | null;
}

/**
 * Check if a given object implements the PolymarketSentimentRequest interface.
 */
export function instanceOfPolymarketSentimentRequest(value: object): value is PolymarketSentimentRequest {
    if (!('topicText' in value) || value['topicText'] === undefined) return false;
    return true;
}

export function PolymarketSentimentRequestFromJSON(json: any): PolymarketSentimentRequest {
    return PolymarketSentimentRequestFromJSONTyped(json, false);
}

export function PolymarketSentimentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolymarketSentimentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'topicText': json['topic_text'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'connectorId': json['connector_id'] == null ? undefined : json['connector_id'],
        'eventUrl': json['event_url'] == null ? undefined : json['event_url'],
        'eventSlug': json['event_slug'] == null ? undefined : json['event_slug'],
        'maxHeadlines': json['max_headlines'] == null ? undefined : json['max_headlines'],
        'refreshIfEmpty': json['refresh_if_empty'] == null ? undefined : json['refresh_if_empty'],
        'credentials': json['credentials'] == null ? undefined : ConnectorCredentialRequestFromJSON(json['credentials']),
    };
}

export function PolymarketSentimentRequestToJSON(json: any): PolymarketSentimentRequest {
    return PolymarketSentimentRequestToJSONTyped(json, false);
}

export function PolymarketSentimentRequestToJSONTyped(value?: PolymarketSentimentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topic_text': value['topicText'],
        'user_id': value['userId'],
        'connector_id': value['connectorId'],
        'event_url': value['eventUrl'],
        'event_slug': value['eventSlug'],
        'max_headlines': value['maxHeadlines'],
        'refresh_if_empty': value['refreshIfEmpty'],
        'credentials': ConnectorCredentialRequestToJSON(value['credentials']),
    };
}

