/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolymarketAuthenticationMeta
 */
export interface PolymarketAuthenticationMeta {
    /**
     * True when the BYO credential is present and validated
     * @type {boolean}
     * @memberof PolymarketAuthenticationMeta
     */
    validatedByApp?: boolean;
    /**
     * True when the upstream vendor still performs auth
     * @type {boolean}
     * @memberof PolymarketAuthenticationMeta
     */
    vendorAuthStillRequired?: boolean;
    /**
     * True when the connector replays the credential upstream
     * @type {boolean}
     * @memberof PolymarketAuthenticationMeta
     */
    appManagesAuthReplay?: boolean;
    /**
     * Human-readable summary of the authentication boundary
     * @type {string}
     * @memberof PolymarketAuthenticationMeta
     */
    message?: string;
}

/**
 * Check if a given object implements the PolymarketAuthenticationMeta interface.
 */
export function instanceOfPolymarketAuthenticationMeta(value: object): value is PolymarketAuthenticationMeta {
    return true;
}

export function PolymarketAuthenticationMetaFromJSON(json: any): PolymarketAuthenticationMeta {
    return PolymarketAuthenticationMetaFromJSONTyped(json, false);
}

export function PolymarketAuthenticationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolymarketAuthenticationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'validatedByApp': json['validated_by_app'] == null ? undefined : json['validated_by_app'],
        'vendorAuthStillRequired': json['vendor_auth_still_required'] == null ? undefined : json['vendor_auth_still_required'],
        'appManagesAuthReplay': json['app_manages_auth_replay'] == null ? undefined : json['app_manages_auth_replay'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PolymarketAuthenticationMetaToJSON(json: any): PolymarketAuthenticationMeta {
    return PolymarketAuthenticationMetaToJSONTyped(json, false);
}

export function PolymarketAuthenticationMetaToJSONTyped(value?: PolymarketAuthenticationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validated_by_app': value['validatedByApp'],
        'vendor_auth_still_required': value['vendorAuthStillRequired'],
        'app_manages_auth_replay': value['appManagesAuthReplay'],
        'message': value['message'],
    };
}

