/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SentimentRequest
 */
export interface SentimentRequest {
    /**
     * Text to analyze
     * @type {string}
     * @memberof SentimentRequest
     */
    text: string;
    /**
     * Specific commodity context
     * @type {string}
     * @memberof SentimentRequest
     */
    commodity?: string | null;
    /**
     * Use enhanced analysis
     * @type {boolean}
     * @memberof SentimentRequest
     */
    enhanced?: boolean;
}

/**
 * Check if a given object implements the SentimentRequest interface.
 */
export function instanceOfSentimentRequest(value: object): value is SentimentRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SentimentRequestFromJSON(json: any): SentimentRequest {
    return SentimentRequestFromJSONTyped(json, false);
}

export function SentimentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SentimentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'commodity': json['commodity'] == null ? undefined : json['commodity'],
        'enhanced': json['enhanced'] == null ? undefined : json['enhanced'],
    };
}

export function SentimentRequestToJSON(json: any): SentimentRequest {
    return SentimentRequestToJSONTyped(json, false);
}

export function SentimentRequestToJSONTyped(value?: SentimentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'commodity': value['commodity'],
        'enhanced': value['enhanced'],
    };
}

