/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SentimentBreakdown
 */
export interface SentimentBreakdown {
    /**
     * Headlines classified bullish
     * @type {number}
     * @memberof SentimentBreakdown
     */
    bullish?: number;
    /**
     * Headlines classified bearish
     * @type {number}
     * @memberof SentimentBreakdown
     */
    bearish?: number;
    /**
     * Headlines classified neutral
     * @type {number}
     * @memberof SentimentBreakdown
     */
    neutral?: number;
}

/**
 * Check if a given object implements the SentimentBreakdown interface.
 */
export function instanceOfSentimentBreakdown(value: object): value is SentimentBreakdown {
    return true;
}

export function SentimentBreakdownFromJSON(json: any): SentimentBreakdown {
    return SentimentBreakdownFromJSONTyped(json, false);
}

export function SentimentBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): SentimentBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'bullish': json['bullish'] == null ? undefined : json['bullish'],
        'bearish': json['bearish'] == null ? undefined : json['bearish'],
        'neutral': json['neutral'] == null ? undefined : json['neutral'],
    };
}

export function SentimentBreakdownToJSON(json: any): SentimentBreakdown {
    return SentimentBreakdownToJSONTyped(json, false);
}

export function SentimentBreakdownToJSONTyped(value?: SentimentBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bullish': value['bullish'],
        'bearish': value['bearish'],
        'neutral': value['neutral'],
    };
}

