/* tslint:disable */
/* eslint-disable */
/**
 * Integra Markets API
 * Commodity-aware sentiment analysis API with prediction-market connectors.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserNewsRequest
 */
export interface UserNewsRequest {
    /**
     * User ID in Supabase
     * @type {string}
     * @memberof UserNewsRequest
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof UserNewsRequest
     */
    maxArticles?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserNewsRequest
     */
    enhancedContent?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof UserNewsRequest
     */
    maxEnhanced?: number | null;
}

/**
 * Check if a given object implements the UserNewsRequest interface.
 */
export function instanceOfUserNewsRequest(value: object): value is UserNewsRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserNewsRequestFromJSON(json: any): UserNewsRequest {
    return UserNewsRequestFromJSONTyped(json, false);
}

export function UserNewsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNewsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'maxArticles': json['max_articles'] == null ? undefined : json['max_articles'],
        'enhancedContent': json['enhanced_content'] == null ? undefined : json['enhanced_content'],
        'maxEnhanced': json['max_enhanced'] == null ? undefined : json['max_enhanced'],
    };
}

export function UserNewsRequestToJSON(json: any): UserNewsRequest {
    return UserNewsRequestToJSONTyped(json, false);
}

export function UserNewsRequestToJSONTyped(value?: UserNewsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'max_articles': value['maxArticles'],
        'enhanced_content': value['enhancedContent'],
        'max_enhanced': value['maxEnhanced'],
    };
}

