"""
    Integra Markets API

    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "integra-markets"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.10"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Integra Markets API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Integra Markets API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with &#x60;Authorization: Bearer &lt;api_key&gt;&#x60;; keys look like &#x60;ik_live_...&#x60; and are created at https://dashboard.integramarkets.app/account/api  **&#x60;sentiment_score&#x60; is signed, -1..+1, 0 &#x3D; neutral** — that is the field to chart. &#x60;confidence&#x60; is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name &#x60;score&#x60;; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.
    """,  # noqa: E501
    package_data={"integra_markets": ["py.typed"]},
)
