# coding: utf-8

"""
    Integra Markets API

    Commodity-aware sentiment analysis API with prediction-market connectors.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AIChatRequest(BaseModel):
    """
    AIChatRequest
    """ # noqa: E501
    messages: List[Dict[str, StrictStr]] = Field(description="Chat messages")
    available_tools: Optional[List[StrictStr]] = Field(default=None, description="Available tools to use")
    commodity: Optional[StrictStr] = Field(default=None, description="Commodity context")
    mode: Optional[StrictStr] = Field(default=None, description="Response mode")
    __properties: ClassVar[List[str]] = ["messages", "available_tools", "commodity", "mode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIChatRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if available_tools (nullable) is None
        # and model_fields_set contains the field
        if self.available_tools is None and "available_tools" in self.model_fields_set:
            _dict['available_tools'] = None

        # set to None if commodity (nullable) is None
        # and model_fields_set contains the field
        if self.commodity is None and "commodity" in self.model_fields_set:
            _dict['commodity'] = None

        # set to None if mode (nullable) is None
        # and model_fields_set contains the field
        if self.mode is None and "mode" in self.model_fields_set:
            _dict['mode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIChatRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messages": obj.get("messages"),
            "available_tools": obj.get("available_tools"),
            "commodity": obj.get("commodity"),
            "mode": obj.get("mode")
        })
        return _obj


