# coding: utf-8

"""
    Integra Markets API

    Commodity news sentiment, narratives and prediction-market divergence.  Authenticate with `Authorization: Bearer <api_key>`; keys look like `ik_live_...` and are created at https://dashboard.integramarkets.app/account/api  **`sentiment_score` is signed, -1..+1, 0 = neutral** — that is the field to chart. `confidence` is a separate magnitude and is NOT directional. Before 2026-09-02 the API exposed the confidence value under the name `score`; bearish rows scored higher than bullish ones, so any cached values from before that date must be discarded.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AskResponse(BaseModel):
    """
    AskResponse
    """ # noqa: E501
    answer: StrictStr
    sources: List[Dict[str, Any]]
    tool_calls: List[Dict[str, Any]]
    model: StrictStr
    template_used: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["answer", "sources", "tool_calls", "model", "template_used"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AskResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if template_used (nullable) is None
        # and model_fields_set contains the field
        if self.template_used is None and "template_used" in self.model_fields_set:
            _dict['template_used'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AskResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "answer": obj.get("answer"),
            "sources": obj.get("sources"),
            "tool_calls": obj.get("tool_calls"),
            "model": obj.get("model"),
            "template_used": obj.get("template_used")
        })
        return _obj


