# coding: utf-8

"""
    Integra Markets API

    Commodity-aware sentiment analysis API with prediction-market connectors.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DashboardSentimentEngineRequest(BaseModel):
    """
    DashboardSentimentEngineRequest
    """ # noqa: E501
    commodities: Optional[List[StrictStr]] = Field(default=None, description="Tracked commodities to include in the dashboard snapshot")
    max_headlines: Optional[Annotated[int, Field(le=50, strict=True, ge=5)]] = Field(default=15, description="Maximum headlines per commodity snapshot")
    refresh_if_empty: Optional[StrictBool] = Field(default=True, description="Fetch headlines if the dashboard cache is empty")
    __properties: ClassVar[List[str]] = ["commodities", "max_headlines", "refresh_if_empty"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardSentimentEngineRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if commodities (nullable) is None
        # and model_fields_set contains the field
        if self.commodities is None and "commodities" in self.model_fields_set:
            _dict['commodities'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardSentimentEngineRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commodities": obj.get("commodities"),
            "max_headlines": obj.get("max_headlines") if obj.get("max_headlines") is not None else 15,
            "refresh_if_empty": obj.get("refresh_if_empty") if obj.get("refresh_if_empty") is not None else True
        })
        return _obj


