# coding: utf-8

"""
    Integra Markets API

    Commodity-aware sentiment analysis API with prediction-market connectors.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NewsRequest(BaseModel):
    """
    NewsRequest
    """ # noqa: E501
    max_articles: Optional[Annotated[int, Field(le=50, strict=True, ge=1)]] = Field(default=None, description="Maximum number of articles to return")
    sources: Optional[List[StrictStr]] = Field(default=None, description="Specific news sources to fetch from")
    commodity_filter: Optional[StrictStr] = Field(default=None, description="Filter for specific commodity")
    hours_back: Optional[Annotated[int, Field(le=168, strict=True, ge=1)]] = Field(default=None, description="Hours back to fetch news from")
    enhanced_content: Optional[StrictBool] = Field(default=None, description="Enable full HTML content extraction and NLTK summarization")
    max_enhanced: Optional[Annotated[int, Field(le=10, strict=True, ge=1)]] = Field(default=None, description="Maximum number of articles to enhance with full content")
    alert_frequency: Optional[StrictStr] = Field(default=None, description="Alert frequency preference (realtime, daily, weekly)")
    min_impact: Optional[StrictStr] = Field(default=None, description="Minimum impact level for alerts (LOW, MEDIUM, HIGH)")
    __properties: ClassVar[List[str]] = ["max_articles", "sources", "commodity_filter", "hours_back", "enhanced_content", "max_enhanced", "alert_frequency", "min_impact"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_articles (nullable) is None
        # and model_fields_set contains the field
        if self.max_articles is None and "max_articles" in self.model_fields_set:
            _dict['max_articles'] = None

        # set to None if sources (nullable) is None
        # and model_fields_set contains the field
        if self.sources is None and "sources" in self.model_fields_set:
            _dict['sources'] = None

        # set to None if commodity_filter (nullable) is None
        # and model_fields_set contains the field
        if self.commodity_filter is None and "commodity_filter" in self.model_fields_set:
            _dict['commodity_filter'] = None

        # set to None if hours_back (nullable) is None
        # and model_fields_set contains the field
        if self.hours_back is None and "hours_back" in self.model_fields_set:
            _dict['hours_back'] = None

        # set to None if enhanced_content (nullable) is None
        # and model_fields_set contains the field
        if self.enhanced_content is None and "enhanced_content" in self.model_fields_set:
            _dict['enhanced_content'] = None

        # set to None if max_enhanced (nullable) is None
        # and model_fields_set contains the field
        if self.max_enhanced is None and "max_enhanced" in self.model_fields_set:
            _dict['max_enhanced'] = None

        # set to None if alert_frequency (nullable) is None
        # and model_fields_set contains the field
        if self.alert_frequency is None and "alert_frequency" in self.model_fields_set:
            _dict['alert_frequency'] = None

        # set to None if min_impact (nullable) is None
        # and model_fields_set contains the field
        if self.min_impact is None and "min_impact" in self.model_fields_set:
            _dict['min_impact'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "max_articles": obj.get("max_articles"),
            "sources": obj.get("sources"),
            "commodity_filter": obj.get("commodity_filter"),
            "hours_back": obj.get("hours_back"),
            "enhanced_content": obj.get("enhanced_content"),
            "max_enhanced": obj.get("max_enhanced"),
            "alert_frequency": obj.get("alert_frequency"),
            "min_impact": obj.get("min_impact")
        })
        return _obj


