# coding: utf-8

"""
    Integra Markets API

    Commodity-aware sentiment analysis API with prediction-market connectors.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OverallSentimentRequest(BaseModel):
    """
    OverallSentimentRequest
    """ # noqa: E501
    topic_text: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Market topic or question to score against recent headlines")
    commodity: Optional[StrictStr] = Field(default=None, description="Optional commodity override")
    max_headlines: Optional[Annotated[int, Field(le=50, strict=True, ge=5)]] = Field(default=20, description="Maximum recent headlines to include")
    refresh_if_empty: Optional[StrictBool] = Field(default=True, description="Fetch the latest feed if the recent-headlines cache is empty")
    event_url: Optional[StrictStr] = Field(default=None, description="Canonical Polymarket event URL for event-driven analysis")
    event_slug: Optional[StrictStr] = Field(default=None, description="Canonical Polymarket event slug")
    __properties: ClassVar[List[str]] = ["topic_text", "commodity", "max_headlines", "refresh_if_empty", "event_url", "event_slug"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OverallSentimentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if commodity (nullable) is None
        # and model_fields_set contains the field
        if self.commodity is None and "commodity" in self.model_fields_set:
            _dict['commodity'] = None

        # set to None if event_url (nullable) is None
        # and model_fields_set contains the field
        if self.event_url is None and "event_url" in self.model_fields_set:
            _dict['event_url'] = None

        # set to None if event_slug (nullable) is None
        # and model_fields_set contains the field
        if self.event_slug is None and "event_slug" in self.model_fields_set:
            _dict['event_slug'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OverallSentimentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "topic_text": obj.get("topic_text"),
            "commodity": obj.get("commodity"),
            "max_headlines": obj.get("max_headlines") if obj.get("max_headlines") is not None else 20,
            "refresh_if_empty": obj.get("refresh_if_empty") if obj.get("refresh_if_empty") is not None else True,
            "event_url": obj.get("event_url"),
            "event_slug": obj.get("event_slug")
        })
        return _obj


