# coding: utf-8

"""
    Integra Markets API

    Commodity-aware sentiment analysis API with prediction-market connectors.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PolymarketConnectorAuthSummary(BaseModel):
    """
    PolymarketConnectorAuthSummary
    """ # noqa: E501
    auth_type: Optional[StrictStr] = Field(default=None, description="Credential mode: none, api_key, or bearer")
    api_key_header: Optional[StrictStr] = Field(default=None, description="Header name when auth_type is api_key")
    has_secret: Optional[StrictBool] = Field(default=False, description="Whether a credential is present")
    masked_secret: Optional[StrictStr] = Field(default=None, description="Masked preview of the credential")
    persisted: Optional[StrictBool] = Field(default=None, description="Whether the credential is stored for reuse")
    __properties: ClassVar[List[str]] = ["auth_type", "api_key_header", "has_secret", "masked_secret", "persisted"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolymarketConnectorAuthSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if auth_type (nullable) is None
        # and model_fields_set contains the field
        if self.auth_type is None and "auth_type" in self.model_fields_set:
            _dict['auth_type'] = None

        # set to None if api_key_header (nullable) is None
        # and model_fields_set contains the field
        if self.api_key_header is None and "api_key_header" in self.model_fields_set:
            _dict['api_key_header'] = None

        # set to None if masked_secret (nullable) is None
        # and model_fields_set contains the field
        if self.masked_secret is None and "masked_secret" in self.model_fields_set:
            _dict['masked_secret'] = None

        # set to None if persisted (nullable) is None
        # and model_fields_set contains the field
        if self.persisted is None and "persisted" in self.model_fields_set:
            _dict['persisted'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolymarketConnectorAuthSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth_type": obj.get("auth_type"),
            "api_key_header": obj.get("api_key_header"),
            "has_secret": obj.get("has_secret") if obj.get("has_secret") is not None else False,
            "masked_secret": obj.get("masked_secret"),
            "persisted": obj.get("persisted")
        })
        return _obj


