# coding: utf-8

"""
    Integra Markets API

    Commodity-aware sentiment analysis API with prediction-market connectors.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from integra_markets.models.polymarket_connector_context import PolymarketConnectorContext
from integra_markets.models.sentiment_breakdown import SentimentBreakdown
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PolymarketSentimentResponse(BaseModel):
    """
    PolymarketSentimentResponse
    """ # noqa: E501
    topic_text: StrictStr = Field(description="Echo of the original request topic")
    primary_target: Optional[StrictStr] = Field(default=None, description="Canonical asset key (internal)")
    commodity: Optional[StrictStr] = Field(default=None, description="Commodity key, alias of primary_target")
    display_name: Optional[StrictStr] = Field(default=None, description="Title-cased commodity name for UI")
    target_assets: Optional[List[StrictStr]] = Field(default=None, description="All inferred asset symbols (uppercase)")
    overall_sentiment: StrictStr = Field(description="One of BULLISH, BEARISH, NEUTRAL")
    confidence: Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Confidence in the overall classification")
    headline_count: Optional[StrictInt] = Field(default=0, description="Number of relevant headlines used")
    summary: StrictStr = Field(description="Human-readable aggregate summary")
    sentiment_breakdown: Optional[SentimentBreakdown] = None
    sample_headlines: Optional[List[StrictStr]] = Field(default=None, description="Up to 5 representative headlines")
    matched_signals: Optional[List[StrictStr]] = Field(default=None, description="Up to 5 keyword features driving the score")
    method: Optional[StrictStr] = Field(default='recent_headlines_cache', description="Identifier of the analyzer used")
    event_url: Optional[StrictStr] = Field(default=None, description="Canonical Polymarket event URL")
    event_slug: Optional[StrictStr] = Field(default=None, description="Canonical Polymarket event slug")
    source_url: Optional[StrictStr] = Field(default=None, description="Canonical source URL (mirrors event_url)")
    cache_timestamp: Optional[StrictStr] = Field(default=None, description="ISO timestamp of the headline cache snapshot")
    connector_context: Optional[PolymarketConnectorContext] = Field(default=None, description="Connector / auth provenance for this response")
    __properties: ClassVar[List[str]] = ["topic_text", "primary_target", "commodity", "display_name", "target_assets", "overall_sentiment", "confidence", "headline_count", "summary", "sentiment_breakdown", "sample_headlines", "matched_signals", "method", "event_url", "event_slug", "source_url", "cache_timestamp", "connector_context"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolymarketSentimentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sentiment_breakdown
        if self.sentiment_breakdown:
            _dict['sentiment_breakdown'] = self.sentiment_breakdown.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connector_context
        if self.connector_context:
            _dict['connector_context'] = self.connector_context.to_dict()
        # set to None if primary_target (nullable) is None
        # and model_fields_set contains the field
        if self.primary_target is None and "primary_target" in self.model_fields_set:
            _dict['primary_target'] = None

        # set to None if commodity (nullable) is None
        # and model_fields_set contains the field
        if self.commodity is None and "commodity" in self.model_fields_set:
            _dict['commodity'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if event_url (nullable) is None
        # and model_fields_set contains the field
        if self.event_url is None and "event_url" in self.model_fields_set:
            _dict['event_url'] = None

        # set to None if event_slug (nullable) is None
        # and model_fields_set contains the field
        if self.event_slug is None and "event_slug" in self.model_fields_set:
            _dict['event_slug'] = None

        # set to None if source_url (nullable) is None
        # and model_fields_set contains the field
        if self.source_url is None and "source_url" in self.model_fields_set:
            _dict['source_url'] = None

        # set to None if cache_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.cache_timestamp is None and "cache_timestamp" in self.model_fields_set:
            _dict['cache_timestamp'] = None

        # set to None if connector_context (nullable) is None
        # and model_fields_set contains the field
        if self.connector_context is None and "connector_context" in self.model_fields_set:
            _dict['connector_context'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolymarketSentimentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "topic_text": obj.get("topic_text"),
            "primary_target": obj.get("primary_target"),
            "commodity": obj.get("commodity"),
            "display_name": obj.get("display_name"),
            "target_assets": obj.get("target_assets"),
            "overall_sentiment": obj.get("overall_sentiment"),
            "confidence": obj.get("confidence"),
            "headline_count": obj.get("headline_count") if obj.get("headline_count") is not None else 0,
            "summary": obj.get("summary"),
            "sentiment_breakdown": SentimentBreakdown.from_dict(obj["sentiment_breakdown"]) if obj.get("sentiment_breakdown") is not None else None,
            "sample_headlines": obj.get("sample_headlines"),
            "matched_signals": obj.get("matched_signals"),
            "method": obj.get("method") if obj.get("method") is not None else 'recent_headlines_cache',
            "event_url": obj.get("event_url"),
            "event_slug": obj.get("event_slug"),
            "source_url": obj.get("source_url"),
            "cache_timestamp": obj.get("cache_timestamp"),
            "connector_context": PolymarketConnectorContext.from_dict(obj["connector_context"]) if obj.get("connector_context") is not None else None
        })
        return _obj


