# coding: utf-8

"""
    Integra Markets API

    Commodity-aware sentiment analysis API with prediction-market connectors.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserNewsRequest(BaseModel):
    """
    UserNewsRequest
    """ # noqa: E501
    user_id: StrictStr = Field(description="User ID in Supabase")
    max_articles: Optional[Annotated[int, Field(le=50, strict=True, ge=1)]] = None
    enhanced_content: Optional[StrictBool] = None
    max_enhanced: Optional[Annotated[int, Field(le=10, strict=True, ge=1)]] = None
    __properties: ClassVar[List[str]] = ["user_id", "max_articles", "enhanced_content", "max_enhanced"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserNewsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_articles (nullable) is None
        # and model_fields_set contains the field
        if self.max_articles is None and "max_articles" in self.model_fields_set:
            _dict['max_articles'] = None

        # set to None if enhanced_content (nullable) is None
        # and model_fields_set contains the field
        if self.enhanced_content is None and "enhanced_content" in self.model_fields_set:
            _dict['enhanced_content'] = None

        # set to None if max_enhanced (nullable) is None
        # and model_fields_set contains the field
        if self.max_enhanced is None and "max_enhanced" in self.model_fields_set:
            _dict['max_enhanced'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserNewsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "max_articles": obj.get("max_articles"),
            "enhanced_content": obj.get("enhanced_content"),
            "max_enhanced": obj.get("max_enhanced")
        })
        return _obj


