name: Deploy to Railway

on:
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy
        run: railway up --service integra-markets
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
